// Code generated by mockery v2.53.5. DO NOT EDIT.

package connection

import (
	context "context"

	connection "github.com/wisp-trading/connectors/pkg/websocket/connection"

	mock "github.com/stretchr/testify/mock"
)

// ConnectionManager is an autogenerated mock type for the ConnectionManager type
type ConnectionManager struct {
	mock.Mock
}

type ConnectionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnectionManager) EXPECT() *ConnectionManager_Expecter {
	return &ConnectionManager_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function with given fields: ctx, websocketUrl
func (_m *ConnectionManager) Connect(ctx context.Context, websocketUrl *string) error {
	ret := _m.Called(ctx, websocketUrl)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) error); ok {
		r0 = rf(ctx, websocketUrl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnectionManager_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type ConnectionManager_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
//   - websocketUrl *string
func (_e *ConnectionManager_Expecter) Connect(ctx interface{}, websocketUrl interface{}) *ConnectionManager_Connect_Call {
	return &ConnectionManager_Connect_Call{Call: _e.mock.On("Connect", ctx, websocketUrl)}
}

func (_c *ConnectionManager_Connect_Call) Run(run func(ctx context.Context, websocketUrl *string)) *ConnectionManager_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string))
	})
	return _c
}

func (_c *ConnectionManager_Connect_Call) Return(_a0 error) *ConnectionManager_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectionManager_Connect_Call) RunAndReturn(run func(context.Context, *string) error) *ConnectionManager_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function with no fields
func (_m *ConnectionManager) Disconnect() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnectionManager_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type ConnectionManager_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
func (_e *ConnectionManager_Expecter) Disconnect() *ConnectionManager_Disconnect_Call {
	return &ConnectionManager_Disconnect_Call{Call: _e.mock.On("Disconnect")}
}

func (_c *ConnectionManager_Disconnect_Call) Run(run func()) *ConnectionManager_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConnectionManager_Disconnect_Call) Return(_a0 error) *ConnectionManager_Disconnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectionManager_Disconnect_Call) RunAndReturn(run func() error) *ConnectionManager_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectionStats provides a mock function with no fields
func (_m *ConnectionManager) GetConnectionStats() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionStats")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// ConnectionManager_GetConnectionStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionStats'
type ConnectionManager_GetConnectionStats_Call struct {
	*mock.Call
}

// GetConnectionStats is a helper method to define mock.On call
func (_e *ConnectionManager_Expecter) GetConnectionStats() *ConnectionManager_GetConnectionStats_Call {
	return &ConnectionManager_GetConnectionStats_Call{Call: _e.mock.On("GetConnectionStats")}
}

func (_c *ConnectionManager_GetConnectionStats_Call) Run(run func()) *ConnectionManager_GetConnectionStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConnectionManager_GetConnectionStats_Call) Return(_a0 map[string]interface{}) *ConnectionManager_GetConnectionStats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectionManager_GetConnectionStats_Call) RunAndReturn(run func() map[string]interface{}) *ConnectionManager_GetConnectionStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetState provides a mock function with no fields
func (_m *ConnectionManager) GetState() connection.ConnectionState {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 connection.ConnectionState
	if rf, ok := ret.Get(0).(func() connection.ConnectionState); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(connection.ConnectionState)
	}

	return r0
}

// ConnectionManager_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type ConnectionManager_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
func (_e *ConnectionManager_Expecter) GetState() *ConnectionManager_GetState_Call {
	return &ConnectionManager_GetState_Call{Call: _e.mock.On("GetState")}
}

func (_c *ConnectionManager_GetState_Call) Run(run func()) *ConnectionManager_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConnectionManager_GetState_Call) Return(_a0 connection.ConnectionState) *ConnectionManager_GetState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectionManager_GetState_Call) RunAndReturn(run func() connection.ConnectionState) *ConnectionManager_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// IsHealthy provides a mock function with no fields
func (_m *ConnectionManager) IsHealthy() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsHealthy")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ConnectionManager_IsHealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsHealthy'
type ConnectionManager_IsHealthy_Call struct {
	*mock.Call
}

// IsHealthy is a helper method to define mock.On call
func (_e *ConnectionManager_Expecter) IsHealthy() *ConnectionManager_IsHealthy_Call {
	return &ConnectionManager_IsHealthy_Call{Call: _e.mock.On("IsHealthy")}
}

func (_c *ConnectionManager_IsHealthy_Call) Run(run func()) *ConnectionManager_IsHealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConnectionManager_IsHealthy_Call) Return(_a0 bool) *ConnectionManager_IsHealthy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectionManager_IsHealthy_Call) RunAndReturn(run func() bool) *ConnectionManager_IsHealthy_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: data
func (_m *ConnectionManager) Send(data []byte) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnectionManager_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type ConnectionManager_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - data []byte
func (_e *ConnectionManager_Expecter) Send(data interface{}) *ConnectionManager_Send_Call {
	return &ConnectionManager_Send_Call{Call: _e.mock.On("Send", data)}
}

func (_c *ConnectionManager_Send_Call) Run(run func(data []byte)) *ConnectionManager_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *ConnectionManager_Send_Call) Return(_a0 error) *ConnectionManager_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectionManager_Send_Call) RunAndReturn(run func([]byte) error) *ConnectionManager_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendJSON provides a mock function with given fields: v
func (_m *ConnectionManager) SendJSON(v interface{}) error {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for SendJSON")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnectionManager_SendJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendJSON'
type ConnectionManager_SendJSON_Call struct {
	*mock.Call
}

// SendJSON is a helper method to define mock.On call
//   - v interface{}
func (_e *ConnectionManager_Expecter) SendJSON(v interface{}) *ConnectionManager_SendJSON_Call {
	return &ConnectionManager_SendJSON_Call{Call: _e.mock.On("SendJSON", v)}
}

func (_c *ConnectionManager_SendJSON_Call) Run(run func(v interface{})) *ConnectionManager_SendJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *ConnectionManager_SendJSON_Call) Return(_a0 error) *ConnectionManager_SendJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectionManager_SendJSON_Call) RunAndReturn(run func(interface{}) error) *ConnectionManager_SendJSON_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function with given fields: data
func (_m *ConnectionManager) SendMessage(data []byte) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnectionManager_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type ConnectionManager_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - data []byte
func (_e *ConnectionManager_Expecter) SendMessage(data interface{}) *ConnectionManager_SendMessage_Call {
	return &ConnectionManager_SendMessage_Call{Call: _e.mock.On("SendMessage", data)}
}

func (_c *ConnectionManager_SendMessage_Call) Run(run func(data []byte)) *ConnectionManager_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *ConnectionManager_SendMessage_Call) Return(_a0 error) *ConnectionManager_SendMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectionManager_SendMessage_Call) RunAndReturn(run func([]byte) error) *ConnectionManager_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendPing provides a mock function with no fields
func (_m *ConnectionManager) SendPing() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendPing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnectionManager_SendPing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPing'
type ConnectionManager_SendPing_Call struct {
	*mock.Call
}

// SendPing is a helper method to define mock.On call
func (_e *ConnectionManager_Expecter) SendPing() *ConnectionManager_SendPing_Call {
	return &ConnectionManager_SendPing_Call{Call: _e.mock.On("SendPing")}
}

func (_c *ConnectionManager_SendPing_Call) Run(run func()) *ConnectionManager_SendPing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConnectionManager_SendPing_Call) Return(_a0 error) *ConnectionManager_SendPing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectionManager_SendPing_Call) RunAndReturn(run func() error) *ConnectionManager_SendPing_Call {
	_c.Call.Return(run)
	return _c
}

// SetCallbacks provides a mock function with given fields: onConnect, onDisconnect, onMessage, onError
func (_m *ConnectionManager) SetCallbacks(onConnect func() error, onDisconnect func() error, onMessage func([]byte) error, onError func(error)) {
	_m.Called(onConnect, onDisconnect, onMessage, onError)
}

// ConnectionManager_SetCallbacks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCallbacks'
type ConnectionManager_SetCallbacks_Call struct {
	*mock.Call
}

// SetCallbacks is a helper method to define mock.On call
//   - onConnect func() error
//   - onDisconnect func() error
//   - onMessage func([]byte) error
//   - onError func(error)
func (_e *ConnectionManager_Expecter) SetCallbacks(onConnect interface{}, onDisconnect interface{}, onMessage interface{}, onError interface{}) *ConnectionManager_SetCallbacks_Call {
	return &ConnectionManager_SetCallbacks_Call{Call: _e.mock.On("SetCallbacks", onConnect, onDisconnect, onMessage, onError)}
}

func (_c *ConnectionManager_SetCallbacks_Call) Run(run func(onConnect func() error, onDisconnect func() error, onMessage func([]byte) error, onError func(error))) *ConnectionManager_SetCallbacks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func() error), args[1].(func() error), args[2].(func([]byte) error), args[3].(func(error)))
	})
	return _c
}

func (_c *ConnectionManager_SetCallbacks_Call) Return() *ConnectionManager_SetCallbacks_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConnectionManager_SetCallbacks_Call) RunAndReturn(run func(func() error, func() error, func([]byte) error, func(error))) *ConnectionManager_SetCallbacks_Call {
	_c.Run(run)
	return _c
}

// NewConnectionManager creates a new instance of ConnectionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnectionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnectionManager {
	mock := &ConnectionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
