// Code generated by mockery v2.53.5. DO NOT EDIT.

package connection

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ReconnectStrategy is an autogenerated mock type for the ReconnectStrategy type
type ReconnectStrategy struct {
	mock.Mock
}

type ReconnectStrategy_Expecter struct {
	mock *mock.Mock
}

func (_m *ReconnectStrategy) EXPECT() *ReconnectStrategy_Expecter {
	return &ReconnectStrategy_Expecter{mock: &_m.Mock}
}

// NextDelay provides a mock function with given fields: attempt
func (_m *ReconnectStrategy) NextDelay(attempt int) time.Duration {
	ret := _m.Called(attempt)

	if len(ret) == 0 {
		panic("no return value specified for NextDelay")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(int) time.Duration); ok {
		r0 = rf(attempt)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// ReconnectStrategy_NextDelay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextDelay'
type ReconnectStrategy_NextDelay_Call struct {
	*mock.Call
}

// NextDelay is a helper method to define mock.On call
//   - attempt int
func (_e *ReconnectStrategy_Expecter) NextDelay(attempt interface{}) *ReconnectStrategy_NextDelay_Call {
	return &ReconnectStrategy_NextDelay_Call{Call: _e.mock.On("NextDelay", attempt)}
}

func (_c *ReconnectStrategy_NextDelay_Call) Run(run func(attempt int)) *ReconnectStrategy_NextDelay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *ReconnectStrategy_NextDelay_Call) Return(_a0 time.Duration) *ReconnectStrategy_NextDelay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReconnectStrategy_NextDelay_Call) RunAndReturn(run func(int) time.Duration) *ReconnectStrategy_NextDelay_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with no fields
func (_m *ReconnectStrategy) Reset() {
	_m.Called()
}

// ReconnectStrategy_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type ReconnectStrategy_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *ReconnectStrategy_Expecter) Reset() *ReconnectStrategy_Reset_Call {
	return &ReconnectStrategy_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *ReconnectStrategy_Reset_Call) Run(run func()) *ReconnectStrategy_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ReconnectStrategy_Reset_Call) Return() *ReconnectStrategy_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *ReconnectStrategy_Reset_Call) RunAndReturn(run func()) *ReconnectStrategy_Reset_Call {
	_c.Run(run)
	return _c
}

// ShouldReconnect provides a mock function with given fields: attempt, err
func (_m *ReconnectStrategy) ShouldReconnect(attempt int, err error) bool {
	ret := _m.Called(attempt, err)

	if len(ret) == 0 {
		panic("no return value specified for ShouldReconnect")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, error) bool); ok {
		r0 = rf(attempt, err)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ReconnectStrategy_ShouldReconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldReconnect'
type ReconnectStrategy_ShouldReconnect_Call struct {
	*mock.Call
}

// ShouldReconnect is a helper method to define mock.On call
//   - attempt int
//   - err error
func (_e *ReconnectStrategy_Expecter) ShouldReconnect(attempt interface{}, err interface{}) *ReconnectStrategy_ShouldReconnect_Call {
	return &ReconnectStrategy_ShouldReconnect_Call{Call: _e.mock.On("ShouldReconnect", attempt, err)}
}

func (_c *ReconnectStrategy_ShouldReconnect_Call) Run(run func(attempt int, err error)) *ReconnectStrategy_ShouldReconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(error))
	})
	return _c
}

func (_c *ReconnectStrategy_ShouldReconnect_Call) Return(_a0 bool) *ReconnectStrategy_ShouldReconnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReconnectStrategy_ShouldReconnect_Call) RunAndReturn(run func(int, error) bool) *ReconnectStrategy_ShouldReconnect_Call {
	_c.Call.Return(run)
	return _c
}

// NewReconnectStrategy creates a new instance of ReconnectStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReconnectStrategy(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReconnectStrategy {
	mock := &ReconnectStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
