// Code generated by mockery v2.53.5. DO NOT EDIT.

package connection

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ReconnectionStrategy is an autogenerated mock type for the ReconnectionStrategy type
type ReconnectionStrategy struct {
	mock.Mock
}

type ReconnectionStrategy_Expecter struct {
	mock *mock.Mock
}

func (_m *ReconnectionStrategy) EXPECT() *ReconnectionStrategy_Expecter {
	return &ReconnectionStrategy_Expecter{mock: &_m.Mock}
}

// MaxAttempts provides a mock function with no fields
func (_m *ReconnectionStrategy) MaxAttempts() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxAttempts")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ReconnectionStrategy_MaxAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxAttempts'
type ReconnectionStrategy_MaxAttempts_Call struct {
	*mock.Call
}

// MaxAttempts is a helper method to define mock.On call
func (_e *ReconnectionStrategy_Expecter) MaxAttempts() *ReconnectionStrategy_MaxAttempts_Call {
	return &ReconnectionStrategy_MaxAttempts_Call{Call: _e.mock.On("MaxAttempts")}
}

func (_c *ReconnectionStrategy_MaxAttempts_Call) Run(run func()) *ReconnectionStrategy_MaxAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ReconnectionStrategy_MaxAttempts_Call) Return(_a0 int) *ReconnectionStrategy_MaxAttempts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReconnectionStrategy_MaxAttempts_Call) RunAndReturn(run func() int) *ReconnectionStrategy_MaxAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// NextDelay provides a mock function with given fields: attempt
func (_m *ReconnectionStrategy) NextDelay(attempt int) time.Duration {
	ret := _m.Called(attempt)

	if len(ret) == 0 {
		panic("no return value specified for NextDelay")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(int) time.Duration); ok {
		r0 = rf(attempt)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// ReconnectionStrategy_NextDelay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextDelay'
type ReconnectionStrategy_NextDelay_Call struct {
	*mock.Call
}

// NextDelay is a helper method to define mock.On call
//   - attempt int
func (_e *ReconnectionStrategy_Expecter) NextDelay(attempt interface{}) *ReconnectionStrategy_NextDelay_Call {
	return &ReconnectionStrategy_NextDelay_Call{Call: _e.mock.On("NextDelay", attempt)}
}

func (_c *ReconnectionStrategy_NextDelay_Call) Run(run func(attempt int)) *ReconnectionStrategy_NextDelay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *ReconnectionStrategy_NextDelay_Call) Return(_a0 time.Duration) *ReconnectionStrategy_NextDelay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReconnectionStrategy_NextDelay_Call) RunAndReturn(run func(int) time.Duration) *ReconnectionStrategy_NextDelay_Call {
	_c.Call.Return(run)
	return _c
}

// NewReconnectionStrategy creates a new instance of ReconnectionStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReconnectionStrategy(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReconnectionStrategy {
	mock := &ReconnectionStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
