// Code generated by mockery v2.53.5. DO NOT EDIT.

package connection

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ReconnectManager is an autogenerated mock type for the ReconnectManager type
type ReconnectManager struct {
	mock.Mock
}

type ReconnectManager_Expecter struct {
	mock *mock.Mock
}

func (_m *ReconnectManager) EXPECT() *ReconnectManager_Expecter {
	return &ReconnectManager_Expecter{mock: &_m.Mock}
}

// SetCallbacks provides a mock function with given fields: onStart, onFail, onSuccess
func (_m *ReconnectManager) SetCallbacks(onStart func(int), onFail func(int, error), onSuccess func(int)) {
	_m.Called(onStart, onFail, onSuccess)
}

// ReconnectManager_SetCallbacks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCallbacks'
type ReconnectManager_SetCallbacks_Call struct {
	*mock.Call
}

// SetCallbacks is a helper method to define mock.On call
//   - onStart func(int)
//   - onFail func(int , error)
//   - onSuccess func(int)
func (_e *ReconnectManager_Expecter) SetCallbacks(onStart interface{}, onFail interface{}, onSuccess interface{}) *ReconnectManager_SetCallbacks_Call {
	return &ReconnectManager_SetCallbacks_Call{Call: _e.mock.On("SetCallbacks", onStart, onFail, onSuccess)}
}

func (_c *ReconnectManager_SetCallbacks_Call) Run(run func(onStart func(int), onFail func(int, error), onSuccess func(int))) *ReconnectManager_SetCallbacks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(int)), args[1].(func(int, error)), args[2].(func(int)))
	})
	return _c
}

func (_c *ReconnectManager_SetCallbacks_Call) Return() *ReconnectManager_SetCallbacks_Call {
	_c.Call.Return()
	return _c
}

func (_c *ReconnectManager_SetCallbacks_Call) RunAndReturn(run func(func(int), func(int, error), func(int))) *ReconnectManager_SetCallbacks_Call {
	_c.Run(run)
	return _c
}

// StartReconnection provides a mock function with given fields: ctx
func (_m *ReconnectManager) StartReconnection(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartReconnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReconnectManager_StartReconnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartReconnection'
type ReconnectManager_StartReconnection_Call struct {
	*mock.Call
}

// StartReconnection is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReconnectManager_Expecter) StartReconnection(ctx interface{}) *ReconnectManager_StartReconnection_Call {
	return &ReconnectManager_StartReconnection_Call{Call: _e.mock.On("StartReconnection", ctx)}
}

func (_c *ReconnectManager_StartReconnection_Call) Run(run func(ctx context.Context)) *ReconnectManager_StartReconnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReconnectManager_StartReconnection_Call) Return(_a0 error) *ReconnectManager_StartReconnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReconnectManager_StartReconnection_Call) RunAndReturn(run func(context.Context) error) *ReconnectManager_StartReconnection_Call {
	_c.Call.Return(run)
	return _c
}

// StopReconnection provides a mock function with no fields
func (_m *ReconnectManager) StopReconnection() {
	_m.Called()
}

// ReconnectManager_StopReconnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopReconnection'
type ReconnectManager_StopReconnection_Call struct {
	*mock.Call
}

// StopReconnection is a helper method to define mock.On call
func (_e *ReconnectManager_Expecter) StopReconnection() *ReconnectManager_StopReconnection_Call {
	return &ReconnectManager_StopReconnection_Call{Call: _e.mock.On("StopReconnection")}
}

func (_c *ReconnectManager_StopReconnection_Call) Run(run func()) *ReconnectManager_StopReconnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ReconnectManager_StopReconnection_Call) Return() *ReconnectManager_StopReconnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *ReconnectManager_StopReconnection_Call) RunAndReturn(run func()) *ReconnectManager_StopReconnection_Call {
	_c.Run(run)
	return _c
}

// NewReconnectManager creates a new instance of ReconnectManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReconnectManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReconnectManager {
	mock := &ReconnectManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
