// Code generated by mockery v2.53.5. DO NOT EDIT.

package connection

import (
	context "context"

	connection "github.com/wisp-trading/connectors/pkg/websocket/connection"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// WebSocketDialer is an autogenerated mock type for the WebSocketDialer type
type WebSocketDialer struct {
	mock.Mock
}

type WebSocketDialer_Expecter struct {
	mock *mock.Mock
}

func (_m *WebSocketDialer) EXPECT() *WebSocketDialer_Expecter {
	return &WebSocketDialer_Expecter{mock: &_m.Mock}
}

// DialContext provides a mock function with given fields: ctx, urlStr, requestHeader
func (_m *WebSocketDialer) DialContext(ctx context.Context, urlStr string, requestHeader http.Header) (connection.WebSocketConn, *http.Response, error) {
	ret := _m.Called(ctx, urlStr, requestHeader)

	if len(ret) == 0 {
		panic("no return value specified for DialContext")
	}

	var r0 connection.WebSocketConn
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, http.Header) (connection.WebSocketConn, *http.Response, error)); ok {
		return rf(ctx, urlStr, requestHeader)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, http.Header) connection.WebSocketConn); ok {
		r0 = rf(ctx, urlStr, requestHeader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(connection.WebSocketConn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, http.Header) *http.Response); ok {
		r1 = rf(ctx, urlStr, requestHeader)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, http.Header) error); ok {
		r2 = rf(ctx, urlStr, requestHeader)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// WebSocketDialer_DialContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DialContext'
type WebSocketDialer_DialContext_Call struct {
	*mock.Call
}

// DialContext is a helper method to define mock.On call
//   - ctx context.Context
//   - urlStr string
//   - requestHeader http.Header
func (_e *WebSocketDialer_Expecter) DialContext(ctx interface{}, urlStr interface{}, requestHeader interface{}) *WebSocketDialer_DialContext_Call {
	return &WebSocketDialer_DialContext_Call{Call: _e.mock.On("DialContext", ctx, urlStr, requestHeader)}
}

func (_c *WebSocketDialer_DialContext_Call) Run(run func(ctx context.Context, urlStr string, requestHeader http.Header)) *WebSocketDialer_DialContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(http.Header))
	})
	return _c
}

func (_c *WebSocketDialer_DialContext_Call) Return(_a0 connection.WebSocketConn, _a1 *http.Response, _a2 error) *WebSocketDialer_DialContext_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *WebSocketDialer_DialContext_Call) RunAndReturn(run func(context.Context, string, http.Header) (connection.WebSocketConn, *http.Response, error)) *WebSocketDialer_DialContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewWebSocketDialer creates a new instance of WebSocketDialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebSocketDialer(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebSocketDialer {
	mock := &WebSocketDialer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
