// Code generated by mockery v2.53.5. DO NOT EDIT.

package security

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AuthProvider is an autogenerated mock type for the AuthProvider type
type AuthProvider struct {
	mock.Mock
}

type AuthProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthProvider) EXPECT() *AuthProvider_Expecter {
	return &AuthProvider_Expecter{mock: &_m.Mock}
}

// GetAuthHeaders provides a mock function with given fields: ctx
func (_m *AuthProvider) GetAuthHeaders(ctx context.Context) (http.Header, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthHeaders")
	}

	var r0 http.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (http.Header, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) http.Header); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthProvider_GetAuthHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthHeaders'
type AuthProvider_GetAuthHeaders_Call struct {
	*mock.Call
}

// GetAuthHeaders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AuthProvider_Expecter) GetAuthHeaders(ctx interface{}) *AuthProvider_GetAuthHeaders_Call {
	return &AuthProvider_GetAuthHeaders_Call{Call: _e.mock.On("GetAuthHeaders", ctx)}
}

func (_c *AuthProvider_GetAuthHeaders_Call) Run(run func(ctx context.Context)) *AuthProvider_GetAuthHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AuthProvider_GetAuthHeaders_Call) Return(_a0 http.Header, _a1 error) *AuthProvider_GetAuthHeaders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthProvider_GetAuthHeaders_Call) RunAndReturn(run func(context.Context) (http.Header, error)) *AuthProvider_GetAuthHeaders_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenExpiry provides a mock function with no fields
func (_m *AuthProvider) GetTokenExpiry() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTokenExpiry")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// AuthProvider_GetTokenExpiry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenExpiry'
type AuthProvider_GetTokenExpiry_Call struct {
	*mock.Call
}

// GetTokenExpiry is a helper method to define mock.On call
func (_e *AuthProvider_Expecter) GetTokenExpiry() *AuthProvider_GetTokenExpiry_Call {
	return &AuthProvider_GetTokenExpiry_Call{Call: _e.mock.On("GetTokenExpiry")}
}

func (_c *AuthProvider_GetTokenExpiry_Call) Run(run func()) *AuthProvider_GetTokenExpiry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthProvider_GetTokenExpiry_Call) Return(_a0 time.Time) *AuthProvider_GetTokenExpiry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthProvider_GetTokenExpiry_Call) RunAndReturn(run func() time.Time) *AuthProvider_GetTokenExpiry_Call {
	_c.Call.Return(run)
	return _c
}

// IsAuthenticated provides a mock function with no fields
func (_m *AuthProvider) IsAuthenticated() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsAuthenticated")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// AuthProvider_IsAuthenticated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAuthenticated'
type AuthProvider_IsAuthenticated_Call struct {
	*mock.Call
}

// IsAuthenticated is a helper method to define mock.On call
func (_e *AuthProvider_Expecter) IsAuthenticated() *AuthProvider_IsAuthenticated_Call {
	return &AuthProvider_IsAuthenticated_Call{Call: _e.mock.On("IsAuthenticated")}
}

func (_c *AuthProvider_IsAuthenticated_Call) Run(run func()) *AuthProvider_IsAuthenticated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthProvider_IsAuthenticated_Call) Return(_a0 bool) *AuthProvider_IsAuthenticated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthProvider_IsAuthenticated_Call) RunAndReturn(run func() bool) *AuthProvider_IsAuthenticated_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx
func (_m *AuthProvider) Refresh(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthProvider_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type AuthProvider_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AuthProvider_Expecter) Refresh(ctx interface{}) *AuthProvider_Refresh_Call {
	return &AuthProvider_Refresh_Call{Call: _e.mock.On("Refresh", ctx)}
}

func (_c *AuthProvider_Refresh_Call) Run(run func(ctx context.Context)) *AuthProvider_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AuthProvider_Refresh_Call) Return(_a0 error) *AuthProvider_Refresh_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthProvider_Refresh_Call) RunAndReturn(run func(context.Context) error) *AuthProvider_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthProvider creates a new instance of AuthProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthProvider {
	mock := &AuthProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
