// Code generated by mockery v2.53.5. DO NOT EDIT.

package security

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AuthManager is an autogenerated mock type for the AuthManager type
type AuthManager struct {
	mock.Mock
}

type AuthManager_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthManager) EXPECT() *AuthManager_Expecter {
	return &AuthManager_Expecter{mock: &_m.Mock}
}

// GetSecureHeaders provides a mock function with given fields: ctx
func (_m *AuthManager) GetSecureHeaders(ctx context.Context) (http.Header, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSecureHeaders")
	}

	var r0 http.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (http.Header, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) http.Header); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthManager_GetSecureHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecureHeaders'
type AuthManager_GetSecureHeaders_Call struct {
	*mock.Call
}

// GetSecureHeaders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AuthManager_Expecter) GetSecureHeaders(ctx interface{}) *AuthManager_GetSecureHeaders_Call {
	return &AuthManager_GetSecureHeaders_Call{Call: _e.mock.On("GetSecureHeaders", ctx)}
}

func (_c *AuthManager_GetSecureHeaders_Call) Run(run func(ctx context.Context)) *AuthManager_GetSecureHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AuthManager_GetSecureHeaders_Call) Return(_a0 http.Header, _a1 error) *AuthManager_GetSecureHeaders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthManager_GetSecureHeaders_Call) RunAndReturn(run func(context.Context) (http.Header, error)) *AuthManager_GetSecureHeaders_Call {
	_c.Call.Return(run)
	return _c
}

// PeriodicRefresh provides a mock function with given fields: ctx, interval
func (_m *AuthManager) PeriodicRefresh(ctx context.Context, interval time.Duration) {
	_m.Called(ctx, interval)
}

// AuthManager_PeriodicRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeriodicRefresh'
type AuthManager_PeriodicRefresh_Call struct {
	*mock.Call
}

// PeriodicRefresh is a helper method to define mock.On call
//   - ctx context.Context
//   - interval time.Duration
func (_e *AuthManager_Expecter) PeriodicRefresh(ctx interface{}, interval interface{}) *AuthManager_PeriodicRefresh_Call {
	return &AuthManager_PeriodicRefresh_Call{Call: _e.mock.On("PeriodicRefresh", ctx, interval)}
}

func (_c *AuthManager_PeriodicRefresh_Call) Run(run func(ctx context.Context, interval time.Duration)) *AuthManager_PeriodicRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *AuthManager_PeriodicRefresh_Call) Return() *AuthManager_PeriodicRefresh_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthManager_PeriodicRefresh_Call) RunAndReturn(run func(context.Context, time.Duration)) *AuthManager_PeriodicRefresh_Call {
	_c.Run(run)
	return _c
}

// ValidateConnection provides a mock function with given fields: ctx
func (_m *AuthManager) ValidateConnection(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ValidateConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthManager_ValidateConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateConnection'
type AuthManager_ValidateConnection_Call struct {
	*mock.Call
}

// ValidateConnection is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AuthManager_Expecter) ValidateConnection(ctx interface{}) *AuthManager_ValidateConnection_Call {
	return &AuthManager_ValidateConnection_Call{Call: _e.mock.On("ValidateConnection", ctx)}
}

func (_c *AuthManager_ValidateConnection_Call) Run(run func(ctx context.Context)) *AuthManager_ValidateConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AuthManager_ValidateConnection_Call) Return(_a0 error) *AuthManager_ValidateConnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthManager_ValidateConnection_Call) RunAndReturn(run func(context.Context) error) *AuthManager_ValidateConnection_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthManager creates a new instance of AuthManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthManager {
	mock := &AuthManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
