// Code generated by mockery v2.53.5. DO NOT EDIT.

package security

import mock "github.com/stretchr/testify/mock"

// MessageValidator is an autogenerated mock type for the MessageValidator type
type MessageValidator struct {
	mock.Mock
}

type MessageValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageValidator) EXPECT() *MessageValidator_Expecter {
	return &MessageValidator_Expecter{mock: &_m.Mock}
}

// ValidateMessage provides a mock function with given fields: message
func (_m *MessageValidator) ValidateMessage(message []byte) error {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for ValidateMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessageValidator_ValidateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateMessage'
type MessageValidator_ValidateMessage_Call struct {
	*mock.Call
}

// ValidateMessage is a helper method to define mock.On call
//   - message []byte
func (_e *MessageValidator_Expecter) ValidateMessage(message interface{}) *MessageValidator_ValidateMessage_Call {
	return &MessageValidator_ValidateMessage_Call{Call: _e.mock.On("ValidateMessage", message)}
}

func (_c *MessageValidator_ValidateMessage_Call) Run(run func(message []byte)) *MessageValidator_ValidateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MessageValidator_ValidateMessage_Call) Return(_a0 error) *MessageValidator_ValidateMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageValidator_ValidateMessage_Call) RunAndReturn(run func([]byte) error) *MessageValidator_ValidateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageValidator creates a new instance of MessageValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageValidator {
	mock := &MessageValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
