// Code generated by mockery v2.53.5. DO NOT EDIT.

package base

import mock "github.com/stretchr/testify/mock"

// BaseService is an autogenerated mock type for the BaseService type
type BaseService struct {
	mock.Mock
}

type BaseService_Expecter struct {
	mock *mock.Mock
}

func (_m *BaseService) EXPECT() *BaseService_Expecter {
	return &BaseService_Expecter{mock: &_m.Mock}
}

// GetMetrics provides a mock function with no fields
func (_m *BaseService) GetMetrics() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// BaseService_GetMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetrics'
type BaseService_GetMetrics_Call struct {
	*mock.Call
}

// GetMetrics is a helper method to define mock.On call
func (_e *BaseService_Expecter) GetMetrics() *BaseService_GetMetrics_Call {
	return &BaseService_GetMetrics_Call{Call: _e.mock.On("GetMetrics")}
}

func (_c *BaseService_GetMetrics_Call) Run(run func()) *BaseService_GetMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BaseService_GetMetrics_Call) Return(_a0 map[string]interface{}) *BaseService_GetMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BaseService_GetMetrics_Call) RunAndReturn(run func() map[string]interface{}) *BaseService_GetMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnected provides a mock function with no fields
func (_m *BaseService) IsConnected() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// BaseService_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type BaseService_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *BaseService_Expecter) IsConnected() *BaseService_IsConnected_Call {
	return &BaseService_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *BaseService_IsConnected_Call) Run(run func()) *BaseService_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BaseService_IsConnected_Call) Return(_a0 bool) *BaseService_IsConnected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BaseService_IsConnected_Call) RunAndReturn(run func() bool) *BaseService_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessMessage provides a mock function with given fields: message, handler
func (_m *BaseService) ProcessMessage(message []byte, handler func([]byte) error) error {
	ret := _m.Called(message, handler)

	if len(ret) == 0 {
		panic("no return value specified for ProcessMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, func([]byte) error) error); ok {
		r0 = rf(message, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BaseService_ProcessMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessMessage'
type BaseService_ProcessMessage_Call struct {
	*mock.Call
}

// ProcessMessage is a helper method to define mock.On call
//   - message []byte
//   - handler func([]byte) error
func (_e *BaseService_Expecter) ProcessMessage(message interface{}, handler interface{}) *BaseService_ProcessMessage_Call {
	return &BaseService_ProcessMessage_Call{Call: _e.mock.On("ProcessMessage", message, handler)}
}

func (_c *BaseService_ProcessMessage_Call) Run(run func(message []byte, handler func([]byte) error)) *BaseService_ProcessMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(func([]byte) error))
	})
	return _c
}

func (_c *BaseService_ProcessMessage_Call) Return(_a0 error) *BaseService_ProcessMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BaseService_ProcessMessage_Call) RunAndReturn(run func([]byte, func([]byte) error) error) *BaseService_ProcessMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SetConnected provides a mock function with given fields: connected
func (_m *BaseService) SetConnected(connected bool) {
	_m.Called(connected)
}

// BaseService_SetConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConnected'
type BaseService_SetConnected_Call struct {
	*mock.Call
}

// SetConnected is a helper method to define mock.On call
//   - connected bool
func (_e *BaseService_Expecter) SetConnected(connected interface{}) *BaseService_SetConnected_Call {
	return &BaseService_SetConnected_Call{Call: _e.mock.On("SetConnected", connected)}
}

func (_c *BaseService_SetConnected_Call) Run(run func(connected bool)) *BaseService_SetConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *BaseService_SetConnected_Call) Return() *BaseService_SetConnected_Call {
	_c.Call.Return()
	return _c
}

func (_c *BaseService_SetConnected_Call) RunAndReturn(run func(bool)) *BaseService_SetConnected_Call {
	_c.Run(run)
	return _c
}

// NewBaseService creates a new instance of BaseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBaseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BaseService {
	mock := &BaseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
