// Code generated by mockery v2.53.5. DO NOT EDIT.

package base

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MessageHandler is an autogenerated mock type for the MessageHandler type
type MessageHandler struct {
	mock.Mock
}

type MessageHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageHandler) EXPECT() *MessageHandler_Expecter {
	return &MessageHandler_Expecter{mock: &_m.Mock}
}

// GetChannels provides a mock function with no fields
func (_m *MessageHandler) GetChannels() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChannels")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MessageHandler_GetChannels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannels'
type MessageHandler_GetChannels_Call struct {
	*mock.Call
}

// GetChannels is a helper method to define mock.On call
func (_e *MessageHandler_Expecter) GetChannels() *MessageHandler_GetChannels_Call {
	return &MessageHandler_GetChannels_Call{Call: _e.mock.On("GetChannels")}
}

func (_c *MessageHandler_GetChannels_Call) Run(run func()) *MessageHandler_GetChannels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MessageHandler_GetChannels_Call) Return(_a0 []string) *MessageHandler_GetChannels_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageHandler_GetChannels_Call) RunAndReturn(run func() []string) *MessageHandler_GetChannels_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageTypes provides a mock function with no fields
func (_m *MessageHandler) GetMessageTypes() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMessageTypes")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MessageHandler_GetMessageTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageTypes'
type MessageHandler_GetMessageTypes_Call struct {
	*mock.Call
}

// GetMessageTypes is a helper method to define mock.On call
func (_e *MessageHandler_Expecter) GetMessageTypes() *MessageHandler_GetMessageTypes_Call {
	return &MessageHandler_GetMessageTypes_Call{Call: _e.mock.On("GetMessageTypes")}
}

func (_c *MessageHandler_GetMessageTypes_Call) Run(run func()) *MessageHandler_GetMessageTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MessageHandler_GetMessageTypes_Call) Return(_a0 []string) *MessageHandler_GetMessageTypes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageHandler_GetMessageTypes_Call) RunAndReturn(run func() []string) *MessageHandler_GetMessageTypes_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function with given fields: ctx, message
func (_m *MessageHandler) Handle(ctx context.Context, message []byte) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessageHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MessageHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - message []byte
func (_e *MessageHandler_Expecter) Handle(ctx interface{}, message interface{}) *MessageHandler_Handle_Call {
	return &MessageHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, message)}
}

func (_c *MessageHandler_Handle_Call) Run(run func(ctx context.Context, message []byte)) *MessageHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MessageHandler_Handle_Call) Return(_a0 error) *MessageHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageHandler_Handle_Call) RunAndReturn(run func(context.Context, []byte) error) *MessageHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageHandler creates a new instance of MessageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageHandler {
	mock := &MessageHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
