// Code generated by mockery v2.53.5. DO NOT EDIT.

package adaptor

import (
	context "context"

	gateapi "github.com/gate/gateapi-go/v7"
	mock "github.com/stretchr/testify/mock"
)

// SpotClient is an autogenerated mock type for the SpotClient type
type SpotClient struct {
	mock.Mock
}

type SpotClient_Expecter struct {
	mock *mock.Mock
}

func (_m *SpotClient) EXPECT() *SpotClient_Expecter {
	return &SpotClient_Expecter{mock: &_m.Mock}
}

// Configure provides a mock function with given fields: apiKey, apiSecret, baseURL
func (_m *SpotClient) Configure(apiKey string, apiSecret string, baseURL string) error {
	ret := _m.Called(apiKey, apiSecret, baseURL)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(apiKey, apiSecret, baseURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SpotClient_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type SpotClient_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - apiKey string
//   - apiSecret string
//   - baseURL string
func (_e *SpotClient_Expecter) Configure(apiKey interface{}, apiSecret interface{}, baseURL interface{}) *SpotClient_Configure_Call {
	return &SpotClient_Configure_Call{Call: _e.mock.On("Configure", apiKey, apiSecret, baseURL)}
}

func (_c *SpotClient_Configure_Call) Run(run func(apiKey string, apiSecret string, baseURL string)) *SpotClient_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *SpotClient_Configure_Call) Return(_a0 error) *SpotClient_Configure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpotClient_Configure_Call) RunAndReturn(run func(string, string, string) error) *SpotClient_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// GetAPIContext provides a mock function with no fields
func (_m *SpotClient) GetAPIContext() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAPIContext")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// SpotClient_GetAPIContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAPIContext'
type SpotClient_GetAPIContext_Call struct {
	*mock.Call
}

// GetAPIContext is a helper method to define mock.On call
func (_e *SpotClient_Expecter) GetAPIContext() *SpotClient_GetAPIContext_Call {
	return &SpotClient_GetAPIContext_Call{Call: _e.mock.On("GetAPIContext")}
}

func (_c *SpotClient_GetAPIContext_Call) Run(run func()) *SpotClient_GetAPIContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SpotClient_GetAPIContext_Call) Return(_a0 context.Context) *SpotClient_GetAPIContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpotClient_GetAPIContext_Call) RunAndReturn(run func() context.Context) *SpotClient_GetAPIContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetSpotApi provides a mock function with no fields
func (_m *SpotClient) GetSpotApi() (*gateapi.APIClient, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSpotApi")
	}

	var r0 *gateapi.APIClient
	var r1 error
	if rf, ok := ret.Get(0).(func() (*gateapi.APIClient, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *gateapi.APIClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateapi.APIClient)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SpotClient_GetSpotApi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSpotApi'
type SpotClient_GetSpotApi_Call struct {
	*mock.Call
}

// GetSpotApi is a helper method to define mock.On call
func (_e *SpotClient_Expecter) GetSpotApi() *SpotClient_GetSpotApi_Call {
	return &SpotClient_GetSpotApi_Call{Call: _e.mock.On("GetSpotApi")}
}

func (_c *SpotClient_GetSpotApi_Call) Run(run func()) *SpotClient_GetSpotApi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SpotClient_GetSpotApi_Call) Return(_a0 *gateapi.APIClient, _a1 error) *SpotClient_GetSpotApi_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SpotClient_GetSpotApi_Call) RunAndReturn(run func() (*gateapi.APIClient, error)) *SpotClient_GetSpotApi_Call {
	_c.Call.Return(run)
	return _c
}

// IsConfigured provides a mock function with no fields
func (_m *SpotClient) IsConfigured() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConfigured")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SpotClient_IsConfigured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConfigured'
type SpotClient_IsConfigured_Call struct {
	*mock.Call
}

// IsConfigured is a helper method to define mock.On call
func (_e *SpotClient_Expecter) IsConfigured() *SpotClient_IsConfigured_Call {
	return &SpotClient_IsConfigured_Call{Call: _e.mock.On("IsConfigured")}
}

func (_c *SpotClient_IsConfigured_Call) Run(run func()) *SpotClient_IsConfigured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SpotClient_IsConfigured_Call) Return(_a0 bool) *SpotClient_IsConfigured_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpotClient_IsConfigured_Call) RunAndReturn(run func() bool) *SpotClient_IsConfigured_Call {
	_c.Call.Return(run)
	return _c
}

// NewSpotClient creates a new instance of SpotClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpotClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpotClient {
	mock := &SpotClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
