// Code generated by mockery v2.53.5. DO NOT EDIT.

package websocket

import (
	hyperliquid "github.com/sonirico/go-hyperliquid"
	mock "github.com/stretchr/testify/mock"

	websocket "github.com/wisp-trading/connectors/pkg/connectors/hyperliquid/websocket"
)

// MessageParser is an autogenerated mock type for the MessageParser type
type MessageParser struct {
	mock.Mock
}

type MessageParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageParser) EXPECT() *MessageParser_Expecter {
	return &MessageParser_Expecter{mock: &_m.Mock}
}

// ParseAccountBalance provides a mock function with given fields: msg
func (_m *MessageParser) ParseAccountBalance(msg hyperliquid.WSMessage) (*websocket.AccountBalanceMessage, error) {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for ParseAccountBalance")
	}

	var r0 *websocket.AccountBalanceMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(hyperliquid.WSMessage) (*websocket.AccountBalanceMessage, error)); ok {
		return rf(msg)
	}
	if rf, ok := ret.Get(0).(func(hyperliquid.WSMessage) *websocket.AccountBalanceMessage); ok {
		r0 = rf(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*websocket.AccountBalanceMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(hyperliquid.WSMessage) error); ok {
		r1 = rf(msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageParser_ParseAccountBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAccountBalance'
type MessageParser_ParseAccountBalance_Call struct {
	*mock.Call
}

// ParseAccountBalance is a helper method to define mock.On call
//   - msg hyperliquid.WSMessage
func (_e *MessageParser_Expecter) ParseAccountBalance(msg interface{}) *MessageParser_ParseAccountBalance_Call {
	return &MessageParser_ParseAccountBalance_Call{Call: _e.mock.On("ParseAccountBalance", msg)}
}

func (_c *MessageParser_ParseAccountBalance_Call) Run(run func(msg hyperliquid.WSMessage)) *MessageParser_ParseAccountBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(hyperliquid.WSMessage))
	})
	return _c
}

func (_c *MessageParser_ParseAccountBalance_Call) Return(_a0 *websocket.AccountBalanceMessage, _a1 error) *MessageParser_ParseAccountBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageParser_ParseAccountBalance_Call) RunAndReturn(run func(hyperliquid.WSMessage) (*websocket.AccountBalanceMessage, error)) *MessageParser_ParseAccountBalance_Call {
	_c.Call.Return(run)
	return _c
}

// ParseFundingRate provides a mock function with given fields: msg
func (_m *MessageParser) ParseFundingRate(msg hyperliquid.WSMessage) (*websocket.FundingRateMessage, error) {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for ParseFundingRate")
	}

	var r0 *websocket.FundingRateMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(hyperliquid.WSMessage) (*websocket.FundingRateMessage, error)); ok {
		return rf(msg)
	}
	if rf, ok := ret.Get(0).(func(hyperliquid.WSMessage) *websocket.FundingRateMessage); ok {
		r0 = rf(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*websocket.FundingRateMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(hyperliquid.WSMessage) error); ok {
		r1 = rf(msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageParser_ParseFundingRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseFundingRate'
type MessageParser_ParseFundingRate_Call struct {
	*mock.Call
}

// ParseFundingRate is a helper method to define mock.On call
//   - msg hyperliquid.WSMessage
func (_e *MessageParser_Expecter) ParseFundingRate(msg interface{}) *MessageParser_ParseFundingRate_Call {
	return &MessageParser_ParseFundingRate_Call{Call: _e.mock.On("ParseFundingRate", msg)}
}

func (_c *MessageParser_ParseFundingRate_Call) Run(run func(msg hyperliquid.WSMessage)) *MessageParser_ParseFundingRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(hyperliquid.WSMessage))
	})
	return _c
}

func (_c *MessageParser_ParseFundingRate_Call) Return(_a0 *websocket.FundingRateMessage, _a1 error) *MessageParser_ParseFundingRate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageParser_ParseFundingRate_Call) RunAndReturn(run func(hyperliquid.WSMessage) (*websocket.FundingRateMessage, error)) *MessageParser_ParseFundingRate_Call {
	_c.Call.Return(run)
	return _c
}

// ParseKline provides a mock function with given fields: msg
func (_m *MessageParser) ParseKline(msg hyperliquid.WSMessage) (*websocket.KlineMessage, error) {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for ParseKline")
	}

	var r0 *websocket.KlineMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(hyperliquid.WSMessage) (*websocket.KlineMessage, error)); ok {
		return rf(msg)
	}
	if rf, ok := ret.Get(0).(func(hyperliquid.WSMessage) *websocket.KlineMessage); ok {
		r0 = rf(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*websocket.KlineMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(hyperliquid.WSMessage) error); ok {
		r1 = rf(msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageParser_ParseKline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseKline'
type MessageParser_ParseKline_Call struct {
	*mock.Call
}

// ParseKline is a helper method to define mock.On call
//   - msg hyperliquid.WSMessage
func (_e *MessageParser_Expecter) ParseKline(msg interface{}) *MessageParser_ParseKline_Call {
	return &MessageParser_ParseKline_Call{Call: _e.mock.On("ParseKline", msg)}
}

func (_c *MessageParser_ParseKline_Call) Run(run func(msg hyperliquid.WSMessage)) *MessageParser_ParseKline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(hyperliquid.WSMessage))
	})
	return _c
}

func (_c *MessageParser_ParseKline_Call) Return(_a0 *websocket.KlineMessage, _a1 error) *MessageParser_ParseKline_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageParser_ParseKline_Call) RunAndReturn(run func(hyperliquid.WSMessage) (*websocket.KlineMessage, error)) *MessageParser_ParseKline_Call {
	_c.Call.Return(run)
	return _c
}

// ParseOrderBook provides a mock function with given fields: msg
func (_m *MessageParser) ParseOrderBook(msg hyperliquid.WSMessage) (*websocket.OrderBookMessage, error) {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for ParseOrderBook")
	}

	var r0 *websocket.OrderBookMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(hyperliquid.WSMessage) (*websocket.OrderBookMessage, error)); ok {
		return rf(msg)
	}
	if rf, ok := ret.Get(0).(func(hyperliquid.WSMessage) *websocket.OrderBookMessage); ok {
		r0 = rf(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*websocket.OrderBookMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(hyperliquid.WSMessage) error); ok {
		r1 = rf(msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageParser_ParseOrderBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseOrderBook'
type MessageParser_ParseOrderBook_Call struct {
	*mock.Call
}

// ParseOrderBook is a helper method to define mock.On call
//   - msg hyperliquid.WSMessage
func (_e *MessageParser_Expecter) ParseOrderBook(msg interface{}) *MessageParser_ParseOrderBook_Call {
	return &MessageParser_ParseOrderBook_Call{Call: _e.mock.On("ParseOrderBook", msg)}
}

func (_c *MessageParser_ParseOrderBook_Call) Run(run func(msg hyperliquid.WSMessage)) *MessageParser_ParseOrderBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(hyperliquid.WSMessage))
	})
	return _c
}

func (_c *MessageParser_ParseOrderBook_Call) Return(_a0 *websocket.OrderBookMessage, _a1 error) *MessageParser_ParseOrderBook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageParser_ParseOrderBook_Call) RunAndReturn(run func(hyperliquid.WSMessage) (*websocket.OrderBookMessage, error)) *MessageParser_ParseOrderBook_Call {
	_c.Call.Return(run)
	return _c
}

// ParsePosition provides a mock function with given fields: msg
func (_m *MessageParser) ParsePosition(msg hyperliquid.WSMessage) (*websocket.PositionMessage, error) {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for ParsePosition")
	}

	var r0 *websocket.PositionMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(hyperliquid.WSMessage) (*websocket.PositionMessage, error)); ok {
		return rf(msg)
	}
	if rf, ok := ret.Get(0).(func(hyperliquid.WSMessage) *websocket.PositionMessage); ok {
		r0 = rf(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*websocket.PositionMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(hyperliquid.WSMessage) error); ok {
		r1 = rf(msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageParser_ParsePosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParsePosition'
type MessageParser_ParsePosition_Call struct {
	*mock.Call
}

// ParsePosition is a helper method to define mock.On call
//   - msg hyperliquid.WSMessage
func (_e *MessageParser_Expecter) ParsePosition(msg interface{}) *MessageParser_ParsePosition_Call {
	return &MessageParser_ParsePosition_Call{Call: _e.mock.On("ParsePosition", msg)}
}

func (_c *MessageParser_ParsePosition_Call) Run(run func(msg hyperliquid.WSMessage)) *MessageParser_ParsePosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(hyperliquid.WSMessage))
	})
	return _c
}

func (_c *MessageParser_ParsePosition_Call) Return(_a0 *websocket.PositionMessage, _a1 error) *MessageParser_ParsePosition_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageParser_ParsePosition_Call) RunAndReturn(run func(hyperliquid.WSMessage) (*websocket.PositionMessage, error)) *MessageParser_ParsePosition_Call {
	_c.Call.Return(run)
	return _c
}

// ParseTrades provides a mock function with given fields: msg
func (_m *MessageParser) ParseTrades(msg hyperliquid.WSMessage) ([]websocket.TradeMessage, error) {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for ParseTrades")
	}

	var r0 []websocket.TradeMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(hyperliquid.WSMessage) ([]websocket.TradeMessage, error)); ok {
		return rf(msg)
	}
	if rf, ok := ret.Get(0).(func(hyperliquid.WSMessage) []websocket.TradeMessage); ok {
		r0 = rf(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]websocket.TradeMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(hyperliquid.WSMessage) error); ok {
		r1 = rf(msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageParser_ParseTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseTrades'
type MessageParser_ParseTrades_Call struct {
	*mock.Call
}

// ParseTrades is a helper method to define mock.On call
//   - msg hyperliquid.WSMessage
func (_e *MessageParser_Expecter) ParseTrades(msg interface{}) *MessageParser_ParseTrades_Call {
	return &MessageParser_ParseTrades_Call{Call: _e.mock.On("ParseTrades", msg)}
}

func (_c *MessageParser_ParseTrades_Call) Run(run func(msg hyperliquid.WSMessage)) *MessageParser_ParseTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(hyperliquid.WSMessage))
	})
	return _c
}

func (_c *MessageParser_ParseTrades_Call) Return(_a0 []websocket.TradeMessage, _a1 error) *MessageParser_ParseTrades_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageParser_ParseTrades_Call) RunAndReturn(run func(hyperliquid.WSMessage) ([]websocket.TradeMessage, error)) *MessageParser_ParseTrades_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageParser creates a new instance of MessageParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageParser {
	mock := &MessageParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
