// Code generated by mockery v2.53.5. DO NOT EDIT.

package adaptor

import (
	context "context"

	bybit_connector "github.com/bybit-exchange/bybit.go.api"

	mock "github.com/stretchr/testify/mock"
)

// PerpClient is an autogenerated mock type for the PerpClient type
type PerpClient struct {
	mock.Mock
}

type PerpClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PerpClient) EXPECT() *PerpClient_Expecter {
	return &PerpClient_Expecter{mock: &_m.Mock}
}

// Configure provides a mock function with given fields: apiKey, apiSecret, baseURL, isTestnet
func (_m *PerpClient) Configure(apiKey string, apiSecret string, baseURL string, isTestnet bool) error {
	ret := _m.Called(apiKey, apiSecret, baseURL, isTestnet)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, bool) error); ok {
		r0 = rf(apiKey, apiSecret, baseURL, isTestnet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PerpClient_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type PerpClient_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - apiKey string
//   - apiSecret string
//   - baseURL string
//   - isTestnet bool
func (_e *PerpClient_Expecter) Configure(apiKey interface{}, apiSecret interface{}, baseURL interface{}, isTestnet interface{}) *PerpClient_Configure_Call {
	return &PerpClient_Configure_Call{Call: _e.mock.On("Configure", apiKey, apiSecret, baseURL, isTestnet)}
}

func (_c *PerpClient_Configure_Call) Run(run func(apiKey string, apiSecret string, baseURL string, isTestnet bool)) *PerpClient_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *PerpClient_Configure_Call) Return(_a0 error) *PerpClient_Configure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PerpClient_Configure_Call) RunAndReturn(run func(string, string, string, bool) error) *PerpClient_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// GetAPIContext provides a mock function with no fields
func (_m *PerpClient) GetAPIContext() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAPIContext")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// PerpClient_GetAPIContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAPIContext'
type PerpClient_GetAPIContext_Call struct {
	*mock.Call
}

// GetAPIContext is a helper method to define mock.On call
func (_e *PerpClient_Expecter) GetAPIContext() *PerpClient_GetAPIContext_Call {
	return &PerpClient_GetAPIContext_Call{Call: _e.mock.On("GetAPIContext")}
}

func (_c *PerpClient_GetAPIContext_Call) Run(run func()) *PerpClient_GetAPIContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PerpClient_GetAPIContext_Call) Return(_a0 context.Context) *PerpClient_GetAPIContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PerpClient_GetAPIContext_Call) RunAndReturn(run func() context.Context) *PerpClient_GetAPIContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetClient provides a mock function with no fields
func (_m *PerpClient) GetClient() (*bybit_connector.Client, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 *bybit_connector.Client
	var r1 error
	if rf, ok := ret.Get(0).(func() (*bybit_connector.Client, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *bybit_connector.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bybit_connector.Client)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PerpClient_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type PerpClient_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
func (_e *PerpClient_Expecter) GetClient() *PerpClient_GetClient_Call {
	return &PerpClient_GetClient_Call{Call: _e.mock.On("GetClient")}
}

func (_c *PerpClient_GetClient_Call) Run(run func()) *PerpClient_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PerpClient_GetClient_Call) Return(_a0 *bybit_connector.Client, _a1 error) *PerpClient_GetClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PerpClient_GetClient_Call) RunAndReturn(run func() (*bybit_connector.Client, error)) *PerpClient_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// IsConfigured provides a mock function with no fields
func (_m *PerpClient) IsConfigured() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConfigured")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PerpClient_IsConfigured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConfigured'
type PerpClient_IsConfigured_Call struct {
	*mock.Call
}

// IsConfigured is a helper method to define mock.On call
func (_e *PerpClient_Expecter) IsConfigured() *PerpClient_IsConfigured_Call {
	return &PerpClient_IsConfigured_Call{Call: _e.mock.On("IsConfigured")}
}

func (_c *PerpClient_IsConfigured_Call) Run(run func()) *PerpClient_IsConfigured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PerpClient_IsConfigured_Call) Return(_a0 bool) *PerpClient_IsConfigured_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PerpClient_IsConfigured_Call) RunAndReturn(run func() bool) *PerpClient_IsConfigured_Call {
	_c.Call.Return(run)
	return _c
}

// NewPerpClient creates a new instance of PerpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPerpClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PerpClient {
	mock := &PerpClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
