// Code generated by mockery v2.53.5. DO NOT EDIT.

package websockets

import (
	mock "github.com/stretchr/testify/mock"
	websockets "github.com/wisp-trading/connectors/pkg/connectors/paradex/websocket"
)

// WebSocketService is an autogenerated mock type for the WebSocketService type
type WebSocketService struct {
	mock.Mock
}

type WebSocketService_Expecter struct {
	mock *mock.Mock
}

func (_m *WebSocketService) EXPECT() *WebSocketService_Expecter {
	return &WebSocketService_Expecter{mock: &_m.Mock}
}

// AccountUpdates provides a mock function with no fields
func (_m *WebSocketService) AccountUpdates() <-chan websockets.AccountUpdate {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AccountUpdates")
	}

	var r0 <-chan websockets.AccountUpdate
	if rf, ok := ret.Get(0).(func() <-chan websockets.AccountUpdate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan websockets.AccountUpdate)
		}
	}

	return r0
}

// WebSocketService_AccountUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccountUpdates'
type WebSocketService_AccountUpdates_Call struct {
	*mock.Call
}

// AccountUpdates is a helper method to define mock.On call
func (_e *WebSocketService_Expecter) AccountUpdates() *WebSocketService_AccountUpdates_Call {
	return &WebSocketService_AccountUpdates_Call{Call: _e.mock.On("AccountUpdates")}
}

func (_c *WebSocketService_AccountUpdates_Call) Run(run func()) *WebSocketService_AccountUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketService_AccountUpdates_Call) Return(_a0 <-chan websockets.AccountUpdate) *WebSocketService_AccountUpdates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_AccountUpdates_Call) RunAndReturn(run func() <-chan websockets.AccountUpdate) *WebSocketService_AccountUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function with no fields
func (_m *WebSocketService) Connect() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WebSocketService_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type WebSocketService_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *WebSocketService_Expecter) Connect() *WebSocketService_Connect_Call {
	return &WebSocketService_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *WebSocketService_Connect_Call) Run(run func()) *WebSocketService_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketService_Connect_Call) Return(_a0 error) *WebSocketService_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_Connect_Call) RunAndReturn(run func() error) *WebSocketService_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function with no fields
func (_m *WebSocketService) Disconnect() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WebSocketService_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type WebSocketService_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
func (_e *WebSocketService_Expecter) Disconnect() *WebSocketService_Disconnect_Call {
	return &WebSocketService_Disconnect_Call{Call: _e.mock.On("Disconnect")}
}

func (_c *WebSocketService_Disconnect_Call) Run(run func()) *WebSocketService_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketService_Disconnect_Call) Return(_a0 error) *WebSocketService_Disconnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_Disconnect_Call) RunAndReturn(run func() error) *WebSocketService_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// ErrorChannel provides a mock function with no fields
func (_m *WebSocketService) ErrorChannel() <-chan error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ErrorChannel")
	}

	var r0 <-chan error
	if rf, ok := ret.Get(0).(func() <-chan error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan error)
		}
	}

	return r0
}

// WebSocketService_ErrorChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorChannel'
type WebSocketService_ErrorChannel_Call struct {
	*mock.Call
}

// ErrorChannel is a helper method to define mock.On call
func (_e *WebSocketService_Expecter) ErrorChannel() *WebSocketService_ErrorChannel_Call {
	return &WebSocketService_ErrorChannel_Call{Call: _e.mock.On("ErrorChannel")}
}

func (_c *WebSocketService_ErrorChannel_Call) Run(run func()) *WebSocketService_ErrorChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketService_ErrorChannel_Call) Return(_a0 <-chan error) *WebSocketService_ErrorChannel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_ErrorChannel_Call) RunAndReturn(run func() <-chan error) *WebSocketService_ErrorChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetrics provides a mock function with no fields
func (_m *WebSocketService) GetMetrics() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// WebSocketService_GetMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetrics'
type WebSocketService_GetMetrics_Call struct {
	*mock.Call
}

// GetMetrics is a helper method to define mock.On call
func (_e *WebSocketService_Expecter) GetMetrics() *WebSocketService_GetMetrics_Call {
	return &WebSocketService_GetMetrics_Call{Call: _e.mock.On("GetMetrics")}
}

func (_c *WebSocketService_GetMetrics_Call) Run(run func()) *WebSocketService_GetMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketService_GetMetrics_Call) Return(_a0 map[string]interface{}) *WebSocketService_GetMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_GetMetrics_Call) RunAndReturn(run func() map[string]interface{}) *WebSocketService_GetMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnected provides a mock function with no fields
func (_m *WebSocketService) IsConnected() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// WebSocketService_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type WebSocketService_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *WebSocketService_Expecter) IsConnected() *WebSocketService_IsConnected_Call {
	return &WebSocketService_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *WebSocketService_IsConnected_Call) Run(run func()) *WebSocketService_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketService_IsConnected_Call) Return(_a0 bool) *WebSocketService_IsConnected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_IsConnected_Call) RunAndReturn(run func() bool) *WebSocketService_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// IsWebSocketConnected provides a mock function with no fields
func (_m *WebSocketService) IsWebSocketConnected() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsWebSocketConnected")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// WebSocketService_IsWebSocketConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsWebSocketConnected'
type WebSocketService_IsWebSocketConnected_Call struct {
	*mock.Call
}

// IsWebSocketConnected is a helper method to define mock.On call
func (_e *WebSocketService_Expecter) IsWebSocketConnected() *WebSocketService_IsWebSocketConnected_Call {
	return &WebSocketService_IsWebSocketConnected_Call{Call: _e.mock.On("IsWebSocketConnected")}
}

func (_c *WebSocketService_IsWebSocketConnected_Call) Run(run func()) *WebSocketService_IsWebSocketConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketService_IsWebSocketConnected_Call) Return(_a0 bool) *WebSocketService_IsWebSocketConnected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_IsWebSocketConnected_Call) RunAndReturn(run func() bool) *WebSocketService_IsWebSocketConnected_Call {
	_c.Call.Return(run)
	return _c
}

// KlineUpdates provides a mock function with no fields
func (_m *WebSocketService) KlineUpdates() <-chan websockets.KlineUpdate {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for KlineUpdates")
	}

	var r0 <-chan websockets.KlineUpdate
	if rf, ok := ret.Get(0).(func() <-chan websockets.KlineUpdate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan websockets.KlineUpdate)
		}
	}

	return r0
}

// WebSocketService_KlineUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KlineUpdates'
type WebSocketService_KlineUpdates_Call struct {
	*mock.Call
}

// KlineUpdates is a helper method to define mock.On call
func (_e *WebSocketService_Expecter) KlineUpdates() *WebSocketService_KlineUpdates_Call {
	return &WebSocketService_KlineUpdates_Call{Call: _e.mock.On("KlineUpdates")}
}

func (_c *WebSocketService_KlineUpdates_Call) Run(run func()) *WebSocketService_KlineUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketService_KlineUpdates_Call) Return(_a0 <-chan websockets.KlineUpdate) *WebSocketService_KlineUpdates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_KlineUpdates_Call) RunAndReturn(run func() <-chan websockets.KlineUpdate) *WebSocketService_KlineUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// OrderbookUpdates provides a mock function with no fields
func (_m *WebSocketService) OrderbookUpdates() <-chan websockets.OrderbookUpdate {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OrderbookUpdates")
	}

	var r0 <-chan websockets.OrderbookUpdate
	if rf, ok := ret.Get(0).(func() <-chan websockets.OrderbookUpdate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan websockets.OrderbookUpdate)
		}
	}

	return r0
}

// WebSocketService_OrderbookUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderbookUpdates'
type WebSocketService_OrderbookUpdates_Call struct {
	*mock.Call
}

// OrderbookUpdates is a helper method to define mock.On call
func (_e *WebSocketService_Expecter) OrderbookUpdates() *WebSocketService_OrderbookUpdates_Call {
	return &WebSocketService_OrderbookUpdates_Call{Call: _e.mock.On("OrderbookUpdates")}
}

func (_c *WebSocketService_OrderbookUpdates_Call) Run(run func()) *WebSocketService_OrderbookUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketService_OrderbookUpdates_Call) Return(_a0 <-chan websockets.OrderbookUpdate) *WebSocketService_OrderbookUpdates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_OrderbookUpdates_Call) RunAndReturn(run func() <-chan websockets.OrderbookUpdate) *WebSocketService_OrderbookUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// StartWebSocket provides a mock function with no fields
func (_m *WebSocketService) StartWebSocket() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartWebSocket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WebSocketService_StartWebSocket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartWebSocket'
type WebSocketService_StartWebSocket_Call struct {
	*mock.Call
}

// StartWebSocket is a helper method to define mock.On call
func (_e *WebSocketService_Expecter) StartWebSocket() *WebSocketService_StartWebSocket_Call {
	return &WebSocketService_StartWebSocket_Call{Call: _e.mock.On("StartWebSocket")}
}

func (_c *WebSocketService_StartWebSocket_Call) Run(run func()) *WebSocketService_StartWebSocket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketService_StartWebSocket_Call) Return(_a0 error) *WebSocketService_StartWebSocket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_StartWebSocket_Call) RunAndReturn(run func() error) *WebSocketService_StartWebSocket_Call {
	_c.Call.Return(run)
	return _c
}

// StopWebSocket provides a mock function with no fields
func (_m *WebSocketService) StopWebSocket() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopWebSocket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WebSocketService_StopWebSocket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopWebSocket'
type WebSocketService_StopWebSocket_Call struct {
	*mock.Call
}

// StopWebSocket is a helper method to define mock.On call
func (_e *WebSocketService_Expecter) StopWebSocket() *WebSocketService_StopWebSocket_Call {
	return &WebSocketService_StopWebSocket_Call{Call: _e.mock.On("StopWebSocket")}
}

func (_c *WebSocketService_StopWebSocket_Call) Run(run func()) *WebSocketService_StopWebSocket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketService_StopWebSocket_Call) Return(_a0 error) *WebSocketService_StopWebSocket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_StopWebSocket_Call) RunAndReturn(run func() error) *WebSocketService_StopWebSocket_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeAccount provides a mock function with no fields
func (_m *WebSocketService) SubscribeAccount() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SubscribeAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WebSocketService_SubscribeAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeAccount'
type WebSocketService_SubscribeAccount_Call struct {
	*mock.Call
}

// SubscribeAccount is a helper method to define mock.On call
func (_e *WebSocketService_Expecter) SubscribeAccount() *WebSocketService_SubscribeAccount_Call {
	return &WebSocketService_SubscribeAccount_Call{Call: _e.mock.On("SubscribeAccount")}
}

func (_c *WebSocketService_SubscribeAccount_Call) Run(run func()) *WebSocketService_SubscribeAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketService_SubscribeAccount_Call) Return(_a0 error) *WebSocketService_SubscribeAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_SubscribeAccount_Call) RunAndReturn(run func() error) *WebSocketService_SubscribeAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeOrderBook provides a mock function with given fields: asset
func (_m *WebSocketService) SubscribeOrderBook(asset string) error {
	ret := _m.Called(asset)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeOrderBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WebSocketService_SubscribeOrderBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeOrderBook'
type WebSocketService_SubscribeOrderBook_Call struct {
	*mock.Call
}

// SubscribeOrderBook is a helper method to define mock.On call
//   - asset string
func (_e *WebSocketService_Expecter) SubscribeOrderBook(asset interface{}) *WebSocketService_SubscribeOrderBook_Call {
	return &WebSocketService_SubscribeOrderBook_Call{Call: _e.mock.On("SubscribeOrderBook", asset)}
}

func (_c *WebSocketService_SubscribeOrderBook_Call) Run(run func(asset string)) *WebSocketService_SubscribeOrderBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *WebSocketService_SubscribeOrderBook_Call) Return(_a0 error) *WebSocketService_SubscribeOrderBook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_SubscribeOrderBook_Call) RunAndReturn(run func(string) error) *WebSocketService_SubscribeOrderBook_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeTrades provides a mock function with given fields: asset
func (_m *WebSocketService) SubscribeTrades(asset string) error {
	ret := _m.Called(asset)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeTrades")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WebSocketService_SubscribeTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeTrades'
type WebSocketService_SubscribeTrades_Call struct {
	*mock.Call
}

// SubscribeTrades is a helper method to define mock.On call
//   - asset string
func (_e *WebSocketService_Expecter) SubscribeTrades(asset interface{}) *WebSocketService_SubscribeTrades_Call {
	return &WebSocketService_SubscribeTrades_Call{Call: _e.mock.On("SubscribeTrades", asset)}
}

func (_c *WebSocketService_SubscribeTrades_Call) Run(run func(asset string)) *WebSocketService_SubscribeTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *WebSocketService_SubscribeTrades_Call) Return(_a0 error) *WebSocketService_SubscribeTrades_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_SubscribeTrades_Call) RunAndReturn(run func(string) error) *WebSocketService_SubscribeTrades_Call {
	_c.Call.Return(run)
	return _c
}

// TradeUpdates provides a mock function with no fields
func (_m *WebSocketService) TradeUpdates() <-chan websockets.TradeUpdate {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TradeUpdates")
	}

	var r0 <-chan websockets.TradeUpdate
	if rf, ok := ret.Get(0).(func() <-chan websockets.TradeUpdate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan websockets.TradeUpdate)
		}
	}

	return r0
}

// WebSocketService_TradeUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TradeUpdates'
type WebSocketService_TradeUpdates_Call struct {
	*mock.Call
}

// TradeUpdates is a helper method to define mock.On call
func (_e *WebSocketService_Expecter) TradeUpdates() *WebSocketService_TradeUpdates_Call {
	return &WebSocketService_TradeUpdates_Call{Call: _e.mock.On("TradeUpdates")}
}

func (_c *WebSocketService_TradeUpdates_Call) Run(run func()) *WebSocketService_TradeUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketService_TradeUpdates_Call) Return(_a0 <-chan websockets.TradeUpdate) *WebSocketService_TradeUpdates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_TradeUpdates_Call) RunAndReturn(run func() <-chan websockets.TradeUpdate) *WebSocketService_TradeUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// UnsubscribeAccount provides a mock function with no fields
func (_m *WebSocketService) UnsubscribeAccount() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UnsubscribeAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WebSocketService_UnsubscribeAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsubscribeAccount'
type WebSocketService_UnsubscribeAccount_Call struct {
	*mock.Call
}

// UnsubscribeAccount is a helper method to define mock.On call
func (_e *WebSocketService_Expecter) UnsubscribeAccount() *WebSocketService_UnsubscribeAccount_Call {
	return &WebSocketService_UnsubscribeAccount_Call{Call: _e.mock.On("UnsubscribeAccount")}
}

func (_c *WebSocketService_UnsubscribeAccount_Call) Run(run func()) *WebSocketService_UnsubscribeAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketService_UnsubscribeAccount_Call) Return(_a0 error) *WebSocketService_UnsubscribeAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_UnsubscribeAccount_Call) RunAndReturn(run func() error) *WebSocketService_UnsubscribeAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UnsubscribeOrderbook provides a mock function with given fields: symbol
func (_m *WebSocketService) UnsubscribeOrderbook(symbol string) error {
	ret := _m.Called(symbol)

	if len(ret) == 0 {
		panic("no return value specified for UnsubscribeOrderbook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(symbol)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WebSocketService_UnsubscribeOrderbook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsubscribeOrderbook'
type WebSocketService_UnsubscribeOrderbook_Call struct {
	*mock.Call
}

// UnsubscribeOrderbook is a helper method to define mock.On call
//   - symbol string
func (_e *WebSocketService_Expecter) UnsubscribeOrderbook(symbol interface{}) *WebSocketService_UnsubscribeOrderbook_Call {
	return &WebSocketService_UnsubscribeOrderbook_Call{Call: _e.mock.On("UnsubscribeOrderbook", symbol)}
}

func (_c *WebSocketService_UnsubscribeOrderbook_Call) Run(run func(symbol string)) *WebSocketService_UnsubscribeOrderbook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *WebSocketService_UnsubscribeOrderbook_Call) Return(_a0 error) *WebSocketService_UnsubscribeOrderbook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_UnsubscribeOrderbook_Call) RunAndReturn(run func(string) error) *WebSocketService_UnsubscribeOrderbook_Call {
	_c.Call.Return(run)
	return _c
}

// UnsubscribeTrades provides a mock function with given fields: symbol
func (_m *WebSocketService) UnsubscribeTrades(symbol string) error {
	ret := _m.Called(symbol)

	if len(ret) == 0 {
		panic("no return value specified for UnsubscribeTrades")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(symbol)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WebSocketService_UnsubscribeTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsubscribeTrades'
type WebSocketService_UnsubscribeTrades_Call struct {
	*mock.Call
}

// UnsubscribeTrades is a helper method to define mock.On call
//   - symbol string
func (_e *WebSocketService_Expecter) UnsubscribeTrades(symbol interface{}) *WebSocketService_UnsubscribeTrades_Call {
	return &WebSocketService_UnsubscribeTrades_Call{Call: _e.mock.On("UnsubscribeTrades", symbol)}
}

func (_c *WebSocketService_UnsubscribeTrades_Call) Run(run func(symbol string)) *WebSocketService_UnsubscribeTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *WebSocketService_UnsubscribeTrades_Call) Return(_a0 error) *WebSocketService_UnsubscribeTrades_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketService_UnsubscribeTrades_Call) RunAndReturn(run func(string) error) *WebSocketService_UnsubscribeTrades_Call {
	_c.Call.Return(run)
	return _c
}

// NewWebSocketService creates a new instance of WebSocketService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebSocketService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebSocketService {
	mock := &WebSocketService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
