// Code generated by mockery v2.53.5. DO NOT EDIT.

package rest

import (
	hyperliquid "github.com/sonirico/go-hyperliquid"
	mock "github.com/stretchr/testify/mock"

	rest "github.com/wisp-trading/connectors/pkg/connectors/hyperliquid/rest"
)

// MarketDataService is an autogenerated mock type for the MarketDataService type
type MarketDataService struct {
	mock.Mock
}

type MarketDataService_Expecter struct {
	mock *mock.Mock
}

func (_m *MarketDataService) EXPECT() *MarketDataService_Expecter {
	return &MarketDataService_Expecter{mock: &_m.Mock}
}

// GetAllAssetContexts provides a mock function with no fields
func (_m *MarketDataService) GetAllAssetContexts() ([]rest.AssetContext, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllAssetContexts")
	}

	var r0 []rest.AssetContext
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]rest.AssetContext, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []rest.AssetContext); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rest.AssetContext)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_GetAllAssetContexts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAssetContexts'
type MarketDataService_GetAllAssetContexts_Call struct {
	*mock.Call
}

// GetAllAssetContexts is a helper method to define mock.On call
func (_e *MarketDataService_Expecter) GetAllAssetContexts() *MarketDataService_GetAllAssetContexts_Call {
	return &MarketDataService_GetAllAssetContexts_Call{Call: _e.mock.On("GetAllAssetContexts")}
}

func (_c *MarketDataService_GetAllAssetContexts_Call) Run(run func()) *MarketDataService_GetAllAssetContexts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MarketDataService_GetAllAssetContexts_Call) Return(_a0 []rest.AssetContext, _a1 error) *MarketDataService_GetAllAssetContexts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_GetAllAssetContexts_Call) RunAndReturn(run func() ([]rest.AssetContext, error)) *MarketDataService_GetAllAssetContexts_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllMids provides a mock function with no fields
func (_m *MarketDataService) GetAllMids() (map[string]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllMids")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_GetAllMids_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMids'
type MarketDataService_GetAllMids_Call struct {
	*mock.Call
}

// GetAllMids is a helper method to define mock.On call
func (_e *MarketDataService_Expecter) GetAllMids() *MarketDataService_GetAllMids_Call {
	return &MarketDataService_GetAllMids_Call{Call: _e.mock.On("GetAllMids")}
}

func (_c *MarketDataService_GetAllMids_Call) Run(run func()) *MarketDataService_GetAllMids_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MarketDataService_GetAllMids_Call) Return(_a0 map[string]string, _a1 error) *MarketDataService_GetAllMids_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_GetAllMids_Call) RunAndReturn(run func() (map[string]string, error)) *MarketDataService_GetAllMids_Call {
	_c.Call.Return(run)
	return _c
}

// GetAssetContext provides a mock function with given fields: coin
func (_m *MarketDataService) GetAssetContext(coin string) (*rest.AssetContext, error) {
	ret := _m.Called(coin)

	if len(ret) == 0 {
		panic("no return value specified for GetAssetContext")
	}

	var r0 *rest.AssetContext
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*rest.AssetContext, error)); ok {
		return rf(coin)
	}
	if rf, ok := ret.Get(0).(func(string) *rest.AssetContext); ok {
		r0 = rf(coin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.AssetContext)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(coin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_GetAssetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssetContext'
type MarketDataService_GetAssetContext_Call struct {
	*mock.Call
}

// GetAssetContext is a helper method to define mock.On call
//   - coin string
func (_e *MarketDataService_Expecter) GetAssetContext(coin interface{}) *MarketDataService_GetAssetContext_Call {
	return &MarketDataService_GetAssetContext_Call{Call: _e.mock.On("GetAssetContext", coin)}
}

func (_c *MarketDataService_GetAssetContext_Call) Run(run func(coin string)) *MarketDataService_GetAssetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MarketDataService_GetAssetContext_Call) Return(_a0 *rest.AssetContext, _a1 error) *MarketDataService_GetAssetContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_GetAssetContext_Call) RunAndReturn(run func(string) (*rest.AssetContext, error)) *MarketDataService_GetAssetContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetCandles provides a mock function with given fields: coin, interval, startTime, endTime
func (_m *MarketDataService) GetCandles(coin string, interval string, startTime int64, endTime int64) ([]hyperliquid.Candle, error) {
	ret := _m.Called(coin, interval, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetCandles")
	}

	var r0 []hyperliquid.Candle
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) ([]hyperliquid.Candle, error)); ok {
		return rf(coin, interval, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) []hyperliquid.Candle); ok {
		r0 = rf(coin, interval, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]hyperliquid.Candle)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int64, int64) error); ok {
		r1 = rf(coin, interval, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_GetCandles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCandles'
type MarketDataService_GetCandles_Call struct {
	*mock.Call
}

// GetCandles is a helper method to define mock.On call
//   - coin string
//   - interval string
//   - startTime int64
//   - endTime int64
func (_e *MarketDataService_Expecter) GetCandles(coin interface{}, interval interface{}, startTime interface{}, endTime interface{}) *MarketDataService_GetCandles_Call {
	return &MarketDataService_GetCandles_Call{Call: _e.mock.On("GetCandles", coin, interval, startTime, endTime)}
}

func (_c *MarketDataService_GetCandles_Call) Run(run func(coin string, interval string, startTime int64, endTime int64)) *MarketDataService_GetCandles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *MarketDataService_GetCandles_Call) Return(_a0 []hyperliquid.Candle, _a1 error) *MarketDataService_GetCandles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_GetCandles_Call) RunAndReturn(run func(string, string, int64, int64) ([]hyperliquid.Candle, error)) *MarketDataService_GetCandles_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistoricalFundingRates provides a mock function with given fields: coin, startTime, endTime
func (_m *MarketDataService) GetHistoricalFundingRates(coin string, startTime int64, endTime int64) ([]hyperliquid.FundingHistory, error) {
	ret := _m.Called(coin, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoricalFundingRates")
	}

	var r0 []hyperliquid.FundingHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int64, int64) ([]hyperliquid.FundingHistory, error)); ok {
		return rf(coin, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(string, int64, int64) []hyperliquid.FundingHistory); ok {
		r0 = rf(coin, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]hyperliquid.FundingHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int64, int64) error); ok {
		r1 = rf(coin, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_GetHistoricalFundingRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistoricalFundingRates'
type MarketDataService_GetHistoricalFundingRates_Call struct {
	*mock.Call
}

// GetHistoricalFundingRates is a helper method to define mock.On call
//   - coin string
//   - startTime int64
//   - endTime int64
func (_e *MarketDataService_Expecter) GetHistoricalFundingRates(coin interface{}, startTime interface{}, endTime interface{}) *MarketDataService_GetHistoricalFundingRates_Call {
	return &MarketDataService_GetHistoricalFundingRates_Call{Call: _e.mock.On("GetHistoricalFundingRates", coin, startTime, endTime)}
}

func (_c *MarketDataService_GetHistoricalFundingRates_Call) Run(run func(coin string, startTime int64, endTime int64)) *MarketDataService_GetHistoricalFundingRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MarketDataService_GetHistoricalFundingRates_Call) Return(_a0 []hyperliquid.FundingHistory, _a1 error) *MarketDataService_GetHistoricalFundingRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_GetHistoricalFundingRates_Call) RunAndReturn(run func(string, int64, int64) ([]hyperliquid.FundingHistory, error)) *MarketDataService_GetHistoricalFundingRates_Call {
	_c.Call.Return(run)
	return _c
}

// GetL2Book provides a mock function with given fields: coin
func (_m *MarketDataService) GetL2Book(coin string) (*hyperliquid.L2Book, error) {
	ret := _m.Called(coin)

	if len(ret) == 0 {
		panic("no return value specified for GetL2Book")
	}

	var r0 *hyperliquid.L2Book
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*hyperliquid.L2Book, error)); ok {
		return rf(coin)
	}
	if rf, ok := ret.Get(0).(func(string) *hyperliquid.L2Book); ok {
		r0 = rf(coin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hyperliquid.L2Book)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(coin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_GetL2Book_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetL2Book'
type MarketDataService_GetL2Book_Call struct {
	*mock.Call
}

// GetL2Book is a helper method to define mock.On call
//   - coin string
func (_e *MarketDataService_Expecter) GetL2Book(coin interface{}) *MarketDataService_GetL2Book_Call {
	return &MarketDataService_GetL2Book_Call{Call: _e.mock.On("GetL2Book", coin)}
}

func (_c *MarketDataService_GetL2Book_Call) Run(run func(coin string)) *MarketDataService_GetL2Book_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MarketDataService_GetL2Book_Call) Return(_a0 *hyperliquid.L2Book, _a1 error) *MarketDataService_GetL2Book_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_GetL2Book_Call) RunAndReturn(run func(string) (*hyperliquid.L2Book, error)) *MarketDataService_GetL2Book_Call {
	_c.Call.Return(run)
	return _c
}

// GetMeta provides a mock function with no fields
func (_m *MarketDataService) GetMeta() (*hyperliquid.Meta, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMeta")
	}

	var r0 *hyperliquid.Meta
	var r1 error
	if rf, ok := ret.Get(0).(func() (*hyperliquid.Meta, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *hyperliquid.Meta); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hyperliquid.Meta)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_GetMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMeta'
type MarketDataService_GetMeta_Call struct {
	*mock.Call
}

// GetMeta is a helper method to define mock.On call
func (_e *MarketDataService_Expecter) GetMeta() *MarketDataService_GetMeta_Call {
	return &MarketDataService_GetMeta_Call{Call: _e.mock.On("GetMeta")}
}

func (_c *MarketDataService_GetMeta_Call) Run(run func()) *MarketDataService_GetMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MarketDataService_GetMeta_Call) Return(_a0 *hyperliquid.Meta, _a1 error) *MarketDataService_GetMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_GetMeta_Call) RunAndReturn(run func() (*hyperliquid.Meta, error)) *MarketDataService_GetMeta_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetaAndAssetCtxs provides a mock function with no fields
func (_m *MarketDataService) GetMetaAndAssetCtxs() (map[string]interface{}, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetaAndAssetCtxs")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]interface{}, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_GetMetaAndAssetCtxs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetaAndAssetCtxs'
type MarketDataService_GetMetaAndAssetCtxs_Call struct {
	*mock.Call
}

// GetMetaAndAssetCtxs is a helper method to define mock.On call
func (_e *MarketDataService_Expecter) GetMetaAndAssetCtxs() *MarketDataService_GetMetaAndAssetCtxs_Call {
	return &MarketDataService_GetMetaAndAssetCtxs_Call{Call: _e.mock.On("GetMetaAndAssetCtxs")}
}

func (_c *MarketDataService_GetMetaAndAssetCtxs_Call) Run(run func()) *MarketDataService_GetMetaAndAssetCtxs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MarketDataService_GetMetaAndAssetCtxs_Call) Return(_a0 map[string]interface{}, _a1 error) *MarketDataService_GetMetaAndAssetCtxs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_GetMetaAndAssetCtxs_Call) RunAndReturn(run func() (map[string]interface{}, error)) *MarketDataService_GetMetaAndAssetCtxs_Call {
	_c.Call.Return(run)
	return _c
}

// GetOpenOrders provides a mock function with given fields: user
func (_m *MarketDataService) GetOpenOrders(user string) ([]hyperliquid.OpenOrder, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GetOpenOrders")
	}

	var r0 []hyperliquid.OpenOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]hyperliquid.OpenOrder, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(string) []hyperliquid.OpenOrder); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]hyperliquid.OpenOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_GetOpenOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOpenOrders'
type MarketDataService_GetOpenOrders_Call struct {
	*mock.Call
}

// GetOpenOrders is a helper method to define mock.On call
//   - user string
func (_e *MarketDataService_Expecter) GetOpenOrders(user interface{}) *MarketDataService_GetOpenOrders_Call {
	return &MarketDataService_GetOpenOrders_Call{Call: _e.mock.On("GetOpenOrders", user)}
}

func (_c *MarketDataService_GetOpenOrders_Call) Run(run func(user string)) *MarketDataService_GetOpenOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MarketDataService_GetOpenOrders_Call) Return(_a0 []hyperliquid.OpenOrder, _a1 error) *MarketDataService_GetOpenOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_GetOpenOrders_Call) RunAndReturn(run func(string) ([]hyperliquid.OpenOrder, error)) *MarketDataService_GetOpenOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetSpotMeta provides a mock function with no fields
func (_m *MarketDataService) GetSpotMeta() (*hyperliquid.SpotMeta, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSpotMeta")
	}

	var r0 *hyperliquid.SpotMeta
	var r1 error
	if rf, ok := ret.Get(0).(func() (*hyperliquid.SpotMeta, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *hyperliquid.SpotMeta); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hyperliquid.SpotMeta)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_GetSpotMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSpotMeta'
type MarketDataService_GetSpotMeta_Call struct {
	*mock.Call
}

// GetSpotMeta is a helper method to define mock.On call
func (_e *MarketDataService_Expecter) GetSpotMeta() *MarketDataService_GetSpotMeta_Call {
	return &MarketDataService_GetSpotMeta_Call{Call: _e.mock.On("GetSpotMeta")}
}

func (_c *MarketDataService_GetSpotMeta_Call) Run(run func()) *MarketDataService_GetSpotMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MarketDataService_GetSpotMeta_Call) Return(_a0 *hyperliquid.SpotMeta, _a1 error) *MarketDataService_GetSpotMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_GetSpotMeta_Call) RunAndReturn(run func() (*hyperliquid.SpotMeta, error)) *MarketDataService_GetSpotMeta_Call {
	_c.Call.Return(run)
	return _c
}

// GetSpotMetaAndAssetCtxs provides a mock function with no fields
func (_m *MarketDataService) GetSpotMetaAndAssetCtxs() (map[string]interface{}, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSpotMetaAndAssetCtxs")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]interface{}, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_GetSpotMetaAndAssetCtxs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSpotMetaAndAssetCtxs'
type MarketDataService_GetSpotMetaAndAssetCtxs_Call struct {
	*mock.Call
}

// GetSpotMetaAndAssetCtxs is a helper method to define mock.On call
func (_e *MarketDataService_Expecter) GetSpotMetaAndAssetCtxs() *MarketDataService_GetSpotMetaAndAssetCtxs_Call {
	return &MarketDataService_GetSpotMetaAndAssetCtxs_Call{Call: _e.mock.On("GetSpotMetaAndAssetCtxs")}
}

func (_c *MarketDataService_GetSpotMetaAndAssetCtxs_Call) Run(run func()) *MarketDataService_GetSpotMetaAndAssetCtxs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MarketDataService_GetSpotMetaAndAssetCtxs_Call) Return(_a0 map[string]interface{}, _a1 error) *MarketDataService_GetSpotMetaAndAssetCtxs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_GetSpotMetaAndAssetCtxs_Call) RunAndReturn(run func() (map[string]interface{}, error)) *MarketDataService_GetSpotMetaAndAssetCtxs_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserFills provides a mock function with given fields: user
func (_m *MarketDataService) GetUserFills(user string) ([]hyperliquid.Fill, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GetUserFills")
	}

	var r0 []hyperliquid.Fill
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]hyperliquid.Fill, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(string) []hyperliquid.Fill); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]hyperliquid.Fill)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_GetUserFills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserFills'
type MarketDataService_GetUserFills_Call struct {
	*mock.Call
}

// GetUserFills is a helper method to define mock.On call
//   - user string
func (_e *MarketDataService_Expecter) GetUserFills(user interface{}) *MarketDataService_GetUserFills_Call {
	return &MarketDataService_GetUserFills_Call{Call: _e.mock.On("GetUserFills", user)}
}

func (_c *MarketDataService_GetUserFills_Call) Run(run func(user string)) *MarketDataService_GetUserFills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MarketDataService_GetUserFills_Call) Return(_a0 []hyperliquid.Fill, _a1 error) *MarketDataService_GetUserFills_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_GetUserFills_Call) RunAndReturn(run func(string) ([]hyperliquid.Fill, error)) *MarketDataService_GetUserFills_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserState provides a mock function with given fields: user
func (_m *MarketDataService) GetUserState(user string) (hyperliquid.UserState, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GetUserState")
	}

	var r0 hyperliquid.UserState
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (hyperliquid.UserState, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(string) hyperliquid.UserState); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(hyperliquid.UserState)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_GetUserState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserState'
type MarketDataService_GetUserState_Call struct {
	*mock.Call
}

// GetUserState is a helper method to define mock.On call
//   - user string
func (_e *MarketDataService_Expecter) GetUserState(user interface{}) *MarketDataService_GetUserState_Call {
	return &MarketDataService_GetUserState_Call{Call: _e.mock.On("GetUserState", user)}
}

func (_c *MarketDataService_GetUserState_Call) Run(run func(user string)) *MarketDataService_GetUserState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MarketDataService_GetUserState_Call) Return(_a0 hyperliquid.UserState, _a1 error) *MarketDataService_GetUserState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_GetUserState_Call) RunAndReturn(run func(string) (hyperliquid.UserState, error)) *MarketDataService_GetUserState_Call {
	_c.Call.Return(run)
	return _c
}

// NameToAsset provides a mock function with given fields: name
func (_m *MarketDataService) NameToAsset(name string) int {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for NameToAsset")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MarketDataService_NameToAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NameToAsset'
type MarketDataService_NameToAsset_Call struct {
	*mock.Call
}

// NameToAsset is a helper method to define mock.On call
//   - name string
func (_e *MarketDataService_Expecter) NameToAsset(name interface{}) *MarketDataService_NameToAsset_Call {
	return &MarketDataService_NameToAsset_Call{Call: _e.mock.On("NameToAsset", name)}
}

func (_c *MarketDataService_NameToAsset_Call) Run(run func(name string)) *MarketDataService_NameToAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MarketDataService_NameToAsset_Call) Return(_a0 int) *MarketDataService_NameToAsset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MarketDataService_NameToAsset_Call) RunAndReturn(run func(string) int) *MarketDataService_NameToAsset_Call {
	_c.Call.Return(run)
	return _c
}

// NewMarketDataService creates a new instance of MarketDataService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketDataService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketDataService {
	mock := &MarketDataService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
