// Code generated by mockery v2.53.5. DO NOT EDIT.

package rest

import (
	hyperliquid "github.com/sonirico/go-hyperliquid"
	mock "github.com/stretchr/testify/mock"
)

// PriceValidator is an autogenerated mock type for the PriceValidator type
type PriceValidator struct {
	mock.Mock
}

type PriceValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *PriceValidator) EXPECT() *PriceValidator_Expecter {
	return &PriceValidator_Expecter{mock: &_m.Mock}
}

// GetTickSize provides a mock function with given fields: coin
func (_m *PriceValidator) GetTickSize(coin string) (float64, error) {
	ret := _m.Called(coin)

	if len(ret) == 0 {
		panic("no return value specified for GetTickSize")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (float64, error)); ok {
		return rf(coin)
	}
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(coin)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(coin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PriceValidator_GetTickSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTickSize'
type PriceValidator_GetTickSize_Call struct {
	*mock.Call
}

// GetTickSize is a helper method to define mock.On call
//   - coin string
func (_e *PriceValidator_Expecter) GetTickSize(coin interface{}) *PriceValidator_GetTickSize_Call {
	return &PriceValidator_GetTickSize_Call{Call: _e.mock.On("GetTickSize", coin)}
}

func (_c *PriceValidator_GetTickSize_Call) Run(run func(coin string)) *PriceValidator_GetTickSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PriceValidator_GetTickSize_Call) Return(_a0 float64, _a1 error) *PriceValidator_GetTickSize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PriceValidator_GetTickSize_Call) RunAndReturn(run func(string) (float64, error)) *PriceValidator_GetTickSize_Call {
	_c.Call.Return(run)
	return _c
}

// LoadAssetInfo provides a mock function with given fields: meta
func (_m *PriceValidator) LoadAssetInfo(meta *hyperliquid.Meta) error {
	ret := _m.Called(meta)

	if len(ret) == 0 {
		panic("no return value specified for LoadAssetInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*hyperliquid.Meta) error); ok {
		r0 = rf(meta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PriceValidator_LoadAssetInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadAssetInfo'
type PriceValidator_LoadAssetInfo_Call struct {
	*mock.Call
}

// LoadAssetInfo is a helper method to define mock.On call
//   - meta *hyperliquid.Meta
func (_e *PriceValidator_Expecter) LoadAssetInfo(meta interface{}) *PriceValidator_LoadAssetInfo_Call {
	return &PriceValidator_LoadAssetInfo_Call{Call: _e.mock.On("LoadAssetInfo", meta)}
}

func (_c *PriceValidator_LoadAssetInfo_Call) Run(run func(meta *hyperliquid.Meta)) *PriceValidator_LoadAssetInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*hyperliquid.Meta))
	})
	return _c
}

func (_c *PriceValidator_LoadAssetInfo_Call) Return(_a0 error) *PriceValidator_LoadAssetInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceValidator_LoadAssetInfo_Call) RunAndReturn(run func(*hyperliquid.Meta) error) *PriceValidator_LoadAssetInfo_Call {
	_c.Call.Return(run)
	return _c
}

// RoundPrice provides a mock function with given fields: coin, price
func (_m *PriceValidator) RoundPrice(coin string, price float64) (float64, error) {
	ret := _m.Called(coin, price)

	if len(ret) == 0 {
		panic("no return value specified for RoundPrice")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, float64) (float64, error)); ok {
		return rf(coin, price)
	}
	if rf, ok := ret.Get(0).(func(string, float64) float64); ok {
		r0 = rf(coin, price)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string, float64) error); ok {
		r1 = rf(coin, price)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PriceValidator_RoundPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoundPrice'
type PriceValidator_RoundPrice_Call struct {
	*mock.Call
}

// RoundPrice is a helper method to define mock.On call
//   - coin string
//   - price float64
func (_e *PriceValidator_Expecter) RoundPrice(coin interface{}, price interface{}) *PriceValidator_RoundPrice_Call {
	return &PriceValidator_RoundPrice_Call{Call: _e.mock.On("RoundPrice", coin, price)}
}

func (_c *PriceValidator_RoundPrice_Call) Run(run func(coin string, price float64)) *PriceValidator_RoundPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64))
	})
	return _c
}

func (_c *PriceValidator_RoundPrice_Call) Return(_a0 float64, _a1 error) *PriceValidator_RoundPrice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PriceValidator_RoundPrice_Call) RunAndReturn(run func(string, float64) (float64, error)) *PriceValidator_RoundPrice_Call {
	_c.Call.Return(run)
	return _c
}

// RoundSize provides a mock function with given fields: coin, size
func (_m *PriceValidator) RoundSize(coin string, size float64) (float64, error) {
	ret := _m.Called(coin, size)

	if len(ret) == 0 {
		panic("no return value specified for RoundSize")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, float64) (float64, error)); ok {
		return rf(coin, size)
	}
	if rf, ok := ret.Get(0).(func(string, float64) float64); ok {
		r0 = rf(coin, size)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string, float64) error); ok {
		r1 = rf(coin, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PriceValidator_RoundSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoundSize'
type PriceValidator_RoundSize_Call struct {
	*mock.Call
}

// RoundSize is a helper method to define mock.On call
//   - coin string
//   - size float64
func (_e *PriceValidator_Expecter) RoundSize(coin interface{}, size interface{}) *PriceValidator_RoundSize_Call {
	return &PriceValidator_RoundSize_Call{Call: _e.mock.On("RoundSize", coin, size)}
}

func (_c *PriceValidator_RoundSize_Call) Run(run func(coin string, size float64)) *PriceValidator_RoundSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64))
	})
	return _c
}

func (_c *PriceValidator_RoundSize_Call) Return(_a0 float64, _a1 error) *PriceValidator_RoundSize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PriceValidator_RoundSize_Call) RunAndReturn(run func(string, float64) (float64, error)) *PriceValidator_RoundSize_Call {
	_c.Call.Return(run)
	return _c
}

// NewPriceValidator creates a new instance of PriceValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceValidator {
	mock := &PriceValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
