// Code generated by mockery v2.53.5. DO NOT EDIT.

package performance

import mock "github.com/stretchr/testify/mock"

// CircuitBreaker is an autogenerated mock type for the CircuitBreaker type
type CircuitBreaker struct {
	mock.Mock
}

type CircuitBreaker_Expecter struct {
	mock *mock.Mock
}

func (_m *CircuitBreaker) EXPECT() *CircuitBreaker_Expecter {
	return &CircuitBreaker_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: fn
func (_m *CircuitBreaker) Execute(fn func() error) error {
	ret := _m.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func() error) error); ok {
		r0 = rf(fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CircuitBreaker_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CircuitBreaker_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - fn func() error
func (_e *CircuitBreaker_Expecter) Execute(fn interface{}) *CircuitBreaker_Execute_Call {
	return &CircuitBreaker_Execute_Call{Call: _e.mock.On("Execute", fn)}
}

func (_c *CircuitBreaker_Execute_Call) Run(run func(fn func() error)) *CircuitBreaker_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func() error))
	})
	return _c
}

func (_c *CircuitBreaker_Execute_Call) Return(_a0 error) *CircuitBreaker_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CircuitBreaker_Execute_Call) RunAndReturn(run func(func() error) error) *CircuitBreaker_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// GetState provides a mock function with no fields
func (_m *CircuitBreaker) GetState() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// CircuitBreaker_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type CircuitBreaker_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
func (_e *CircuitBreaker_Expecter) GetState() *CircuitBreaker_GetState_Call {
	return &CircuitBreaker_GetState_Call{Call: _e.mock.On("GetState")}
}

func (_c *CircuitBreaker_GetState_Call) Run(run func()) *CircuitBreaker_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CircuitBreaker_GetState_Call) Return(_a0 string) *CircuitBreaker_GetState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CircuitBreaker_GetState_Call) RunAndReturn(run func() string) *CircuitBreaker_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// NewCircuitBreaker creates a new instance of CircuitBreaker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCircuitBreaker(t interface {
	mock.TestingT
	Cleanup(func())
}) *CircuitBreaker {
	mock := &CircuitBreaker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
