// Code generated by mockery v2.53.5. DO NOT EDIT.

package performance

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Metrics is an autogenerated mock type for the Metrics type
type Metrics struct {
	mock.Mock
}

type Metrics_Expecter struct {
	mock *mock.Mock
}

func (_m *Metrics) EXPECT() *Metrics_Expecter {
	return &Metrics_Expecter{mock: &_m.Mock}
}

// GetStats provides a mock function with no fields
func (_m *Metrics) GetStats() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// Metrics_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type Metrics_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
func (_e *Metrics_Expecter) GetStats() *Metrics_GetStats_Call {
	return &Metrics_GetStats_Call{Call: _e.mock.On("GetStats")}
}

func (_c *Metrics_GetStats_Call) Run(run func()) *Metrics_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Metrics_GetStats_Call) Return(_a0 map[string]interface{}) *Metrics_GetStats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Metrics_GetStats_Call) RunAndReturn(run func() map[string]interface{}) *Metrics_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementConnectionError provides a mock function with no fields
func (_m *Metrics) IncrementConnectionError() {
	_m.Called()
}

// Metrics_IncrementConnectionError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementConnectionError'
type Metrics_IncrementConnectionError_Call struct {
	*mock.Call
}

// IncrementConnectionError is a helper method to define mock.On call
func (_e *Metrics_Expecter) IncrementConnectionError() *Metrics_IncrementConnectionError_Call {
	return &Metrics_IncrementConnectionError_Call{Call: _e.mock.On("IncrementConnectionError")}
}

func (_c *Metrics_IncrementConnectionError_Call) Run(run func()) *Metrics_IncrementConnectionError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Metrics_IncrementConnectionError_Call) Return() *Metrics_IncrementConnectionError_Call {
	_c.Call.Return()
	return _c
}

func (_c *Metrics_IncrementConnectionError_Call) RunAndReturn(run func()) *Metrics_IncrementConnectionError_Call {
	_c.Run(run)
	return _c
}

// IncrementDropped provides a mock function with no fields
func (_m *Metrics) IncrementDropped() {
	_m.Called()
}

// Metrics_IncrementDropped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementDropped'
type Metrics_IncrementDropped_Call struct {
	*mock.Call
}

// IncrementDropped is a helper method to define mock.On call
func (_e *Metrics_Expecter) IncrementDropped() *Metrics_IncrementDropped_Call {
	return &Metrics_IncrementDropped_Call{Call: _e.mock.On("IncrementDropped")}
}

func (_c *Metrics_IncrementDropped_Call) Run(run func()) *Metrics_IncrementDropped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Metrics_IncrementDropped_Call) Return() *Metrics_IncrementDropped_Call {
	_c.Call.Return()
	return _c
}

func (_c *Metrics_IncrementDropped_Call) RunAndReturn(run func()) *Metrics_IncrementDropped_Call {
	_c.Run(run)
	return _c
}

// IncrementProcessed provides a mock function with given fields: latency
func (_m *Metrics) IncrementProcessed(latency time.Duration) {
	_m.Called(latency)
}

// Metrics_IncrementProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementProcessed'
type Metrics_IncrementProcessed_Call struct {
	*mock.Call
}

// IncrementProcessed is a helper method to define mock.On call
//   - latency time.Duration
func (_e *Metrics_Expecter) IncrementProcessed(latency interface{}) *Metrics_IncrementProcessed_Call {
	return &Metrics_IncrementProcessed_Call{Call: _e.mock.On("IncrementProcessed", latency)}
}

func (_c *Metrics_IncrementProcessed_Call) Run(run func(latency time.Duration)) *Metrics_IncrementProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *Metrics_IncrementProcessed_Call) Return() *Metrics_IncrementProcessed_Call {
	_c.Call.Return()
	return _c
}

func (_c *Metrics_IncrementProcessed_Call) RunAndReturn(run func(time.Duration)) *Metrics_IncrementProcessed_Call {
	_c.Run(run)
	return _c
}

// IncrementReceived provides a mock function with no fields
func (_m *Metrics) IncrementReceived() {
	_m.Called()
}

// Metrics_IncrementReceived_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementReceived'
type Metrics_IncrementReceived_Call struct {
	*mock.Call
}

// IncrementReceived is a helper method to define mock.On call
func (_e *Metrics_Expecter) IncrementReceived() *Metrics_IncrementReceived_Call {
	return &Metrics_IncrementReceived_Call{Call: _e.mock.On("IncrementReceived")}
}

func (_c *Metrics_IncrementReceived_Call) Run(run func()) *Metrics_IncrementReceived_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Metrics_IncrementReceived_Call) Return() *Metrics_IncrementReceived_Call {
	_c.Call.Return()
	return _c
}

func (_c *Metrics_IncrementReceived_Call) RunAndReturn(run func()) *Metrics_IncrementReceived_Call {
	_c.Run(run)
	return _c
}

// IncrementReconnection provides a mock function with no fields
func (_m *Metrics) IncrementReconnection() {
	_m.Called()
}

// Metrics_IncrementReconnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementReconnection'
type Metrics_IncrementReconnection_Call struct {
	*mock.Call
}

// IncrementReconnection is a helper method to define mock.On call
func (_e *Metrics_Expecter) IncrementReconnection() *Metrics_IncrementReconnection_Call {
	return &Metrics_IncrementReconnection_Call{Call: _e.mock.On("IncrementReconnection")}
}

func (_c *Metrics_IncrementReconnection_Call) Run(run func()) *Metrics_IncrementReconnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Metrics_IncrementReconnection_Call) Return() *Metrics_IncrementReconnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *Metrics_IncrementReconnection_Call) RunAndReturn(run func()) *Metrics_IncrementReconnection_Call {
	_c.Run(run)
	return _c
}

// NewMetrics creates a new instance of Metrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *Metrics {
	mock := &Metrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
