// Code generated by mockery v2.53.5. DO NOT EDIT.

package data

import (
	data "github.com/wisp-trading/connectors/pkg/connectors/bybit/data"
	connector "github.com/wisp-trading/sdk/pkg/types/connector"

	mock "github.com/stretchr/testify/mock"

	perp "github.com/wisp-trading/sdk/pkg/types/connector/perp"

	portfolio "github.com/wisp-trading/sdk/pkg/types/portfolio"
)

// MarketDataService is an autogenerated mock type for the MarketDataService type
type MarketDataService struct {
	mock.Mock
}

type MarketDataService_Expecter struct {
	mock *mock.Mock
}

func (_m *MarketDataService) EXPECT() *MarketDataService_Expecter {
	return &MarketDataService_Expecter{mock: &_m.Mock}
}

// FetchAvailablePerpetualAssets provides a mock function with no fields
func (_m *MarketDataService) FetchAvailablePerpetualAssets() ([]portfolio.Asset, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchAvailablePerpetualAssets")
	}

	var r0 []portfolio.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]portfolio.Asset, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []portfolio.Asset); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]portfolio.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_FetchAvailablePerpetualAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAvailablePerpetualAssets'
type MarketDataService_FetchAvailablePerpetualAssets_Call struct {
	*mock.Call
}

// FetchAvailablePerpetualAssets is a helper method to define mock.On call
func (_e *MarketDataService_Expecter) FetchAvailablePerpetualAssets() *MarketDataService_FetchAvailablePerpetualAssets_Call {
	return &MarketDataService_FetchAvailablePerpetualAssets_Call{Call: _e.mock.On("FetchAvailablePerpetualAssets")}
}

func (_c *MarketDataService_FetchAvailablePerpetualAssets_Call) Run(run func()) *MarketDataService_FetchAvailablePerpetualAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MarketDataService_FetchAvailablePerpetualAssets_Call) Return(_a0 []portfolio.Asset, _a1 error) *MarketDataService_FetchAvailablePerpetualAssets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_FetchAvailablePerpetualAssets_Call) RunAndReturn(run func() ([]portfolio.Asset, error)) *MarketDataService_FetchAvailablePerpetualAssets_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAvailableSpotAssets provides a mock function with no fields
func (_m *MarketDataService) FetchAvailableSpotAssets() ([]portfolio.Asset, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchAvailableSpotAssets")
	}

	var r0 []portfolio.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]portfolio.Asset, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []portfolio.Asset); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]portfolio.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_FetchAvailableSpotAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAvailableSpotAssets'
type MarketDataService_FetchAvailableSpotAssets_Call struct {
	*mock.Call
}

// FetchAvailableSpotAssets is a helper method to define mock.On call
func (_e *MarketDataService_Expecter) FetchAvailableSpotAssets() *MarketDataService_FetchAvailableSpotAssets_Call {
	return &MarketDataService_FetchAvailableSpotAssets_Call{Call: _e.mock.On("FetchAvailableSpotAssets")}
}

func (_c *MarketDataService_FetchAvailableSpotAssets_Call) Run(run func()) *MarketDataService_FetchAvailableSpotAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MarketDataService_FetchAvailableSpotAssets_Call) Return(_a0 []portfolio.Asset, _a1 error) *MarketDataService_FetchAvailableSpotAssets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_FetchAvailableSpotAssets_Call) RunAndReturn(run func() ([]portfolio.Asset, error)) *MarketDataService_FetchAvailableSpotAssets_Call {
	_c.Call.Return(run)
	return _c
}

// FetchCurrentFundingRates provides a mock function with no fields
func (_m *MarketDataService) FetchCurrentFundingRates() (map[portfolio.Asset]perp.FundingRate, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchCurrentFundingRates")
	}

	var r0 map[portfolio.Asset]perp.FundingRate
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[portfolio.Asset]perp.FundingRate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[portfolio.Asset]perp.FundingRate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[portfolio.Asset]perp.FundingRate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_FetchCurrentFundingRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchCurrentFundingRates'
type MarketDataService_FetchCurrentFundingRates_Call struct {
	*mock.Call
}

// FetchCurrentFundingRates is a helper method to define mock.On call
func (_e *MarketDataService_Expecter) FetchCurrentFundingRates() *MarketDataService_FetchCurrentFundingRates_Call {
	return &MarketDataService_FetchCurrentFundingRates_Call{Call: _e.mock.On("FetchCurrentFundingRates")}
}

func (_c *MarketDataService_FetchCurrentFundingRates_Call) Run(run func()) *MarketDataService_FetchCurrentFundingRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MarketDataService_FetchCurrentFundingRates_Call) Return(_a0 map[portfolio.Asset]perp.FundingRate, _a1 error) *MarketDataService_FetchCurrentFundingRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_FetchCurrentFundingRates_Call) RunAndReturn(run func() (map[portfolio.Asset]perp.FundingRate, error)) *MarketDataService_FetchCurrentFundingRates_Call {
	_c.Call.Return(run)
	return _c
}

// FetchFundingRate provides a mock function with given fields: symbol
func (_m *MarketDataService) FetchFundingRate(symbol string) (*perp.FundingRate, error) {
	ret := _m.Called(symbol)

	if len(ret) == 0 {
		panic("no return value specified for FetchFundingRate")
	}

	var r0 *perp.FundingRate
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*perp.FundingRate, error)); ok {
		return rf(symbol)
	}
	if rf, ok := ret.Get(0).(func(string) *perp.FundingRate); ok {
		r0 = rf(symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*perp.FundingRate)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_FetchFundingRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchFundingRate'
type MarketDataService_FetchFundingRate_Call struct {
	*mock.Call
}

// FetchFundingRate is a helper method to define mock.On call
//   - symbol string
func (_e *MarketDataService_Expecter) FetchFundingRate(symbol interface{}) *MarketDataService_FetchFundingRate_Call {
	return &MarketDataService_FetchFundingRate_Call{Call: _e.mock.On("FetchFundingRate", symbol)}
}

func (_c *MarketDataService_FetchFundingRate_Call) Run(run func(symbol string)) *MarketDataService_FetchFundingRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MarketDataService_FetchFundingRate_Call) Return(_a0 *perp.FundingRate, _a1 error) *MarketDataService_FetchFundingRate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_FetchFundingRate_Call) RunAndReturn(run func(string) (*perp.FundingRate, error)) *MarketDataService_FetchFundingRate_Call {
	_c.Call.Return(run)
	return _c
}

// FetchHistoricalFundingRates provides a mock function with given fields: symbol, startTime, endTime
func (_m *MarketDataService) FetchHistoricalFundingRates(symbol string, startTime int64, endTime int64) ([]perp.HistoricalFundingRate, error) {
	ret := _m.Called(symbol, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for FetchHistoricalFundingRates")
	}

	var r0 []perp.HistoricalFundingRate
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int64, int64) ([]perp.HistoricalFundingRate, error)); ok {
		return rf(symbol, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(string, int64, int64) []perp.HistoricalFundingRate); ok {
		r0 = rf(symbol, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]perp.HistoricalFundingRate)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int64, int64) error); ok {
		r1 = rf(symbol, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_FetchHistoricalFundingRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchHistoricalFundingRates'
type MarketDataService_FetchHistoricalFundingRates_Call struct {
	*mock.Call
}

// FetchHistoricalFundingRates is a helper method to define mock.On call
//   - symbol string
//   - startTime int64
//   - endTime int64
func (_e *MarketDataService_Expecter) FetchHistoricalFundingRates(symbol interface{}, startTime interface{}, endTime interface{}) *MarketDataService_FetchHistoricalFundingRates_Call {
	return &MarketDataService_FetchHistoricalFundingRates_Call{Call: _e.mock.On("FetchHistoricalFundingRates", symbol, startTime, endTime)}
}

func (_c *MarketDataService_FetchHistoricalFundingRates_Call) Run(run func(symbol string, startTime int64, endTime int64)) *MarketDataService_FetchHistoricalFundingRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MarketDataService_FetchHistoricalFundingRates_Call) Return(_a0 []perp.HistoricalFundingRate, _a1 error) *MarketDataService_FetchHistoricalFundingRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_FetchHistoricalFundingRates_Call) RunAndReturn(run func(string, int64, int64) ([]perp.HistoricalFundingRate, error)) *MarketDataService_FetchHistoricalFundingRates_Call {
	_c.Call.Return(run)
	return _c
}

// FetchKlines provides a mock function with given fields: symbol, interval, limit
func (_m *MarketDataService) FetchKlines(symbol string, interval string, limit int) ([]connector.Kline, error) {
	ret := _m.Called(symbol, interval, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchKlines")
	}

	var r0 []connector.Kline
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int) ([]connector.Kline, error)); ok {
		return rf(symbol, interval, limit)
	}
	if rf, ok := ret.Get(0).(func(string, string, int) []connector.Kline); ok {
		r0 = rf(symbol, interval, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Kline)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int) error); ok {
		r1 = rf(symbol, interval, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_FetchKlines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchKlines'
type MarketDataService_FetchKlines_Call struct {
	*mock.Call
}

// FetchKlines is a helper method to define mock.On call
//   - symbol string
//   - interval string
//   - limit int
func (_e *MarketDataService_Expecter) FetchKlines(symbol interface{}, interval interface{}, limit interface{}) *MarketDataService_FetchKlines_Call {
	return &MarketDataService_FetchKlines_Call{Call: _e.mock.On("FetchKlines", symbol, interval, limit)}
}

func (_c *MarketDataService_FetchKlines_Call) Run(run func(symbol string, interval string, limit int)) *MarketDataService_FetchKlines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MarketDataService_FetchKlines_Call) Return(_a0 []connector.Kline, _a1 error) *MarketDataService_FetchKlines_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_FetchKlines_Call) RunAndReturn(run func(string, string, int) ([]connector.Kline, error)) *MarketDataService_FetchKlines_Call {
	_c.Call.Return(run)
	return _c
}

// FetchOrderBook provides a mock function with given fields: symbol, depth
func (_m *MarketDataService) FetchOrderBook(symbol string, depth int) (*connector.OrderBook, error) {
	ret := _m.Called(symbol, depth)

	if len(ret) == 0 {
		panic("no return value specified for FetchOrderBook")
	}

	var r0 *connector.OrderBook
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (*connector.OrderBook, error)); ok {
		return rf(symbol, depth)
	}
	if rf, ok := ret.Get(0).(func(string, int) *connector.OrderBook); ok {
		r0 = rf(symbol, depth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.OrderBook)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(symbol, depth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_FetchOrderBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOrderBook'
type MarketDataService_FetchOrderBook_Call struct {
	*mock.Call
}

// FetchOrderBook is a helper method to define mock.On call
//   - symbol string
//   - depth int
func (_e *MarketDataService_Expecter) FetchOrderBook(symbol interface{}, depth interface{}) *MarketDataService_FetchOrderBook_Call {
	return &MarketDataService_FetchOrderBook_Call{Call: _e.mock.On("FetchOrderBook", symbol, depth)}
}

func (_c *MarketDataService_FetchOrderBook_Call) Run(run func(symbol string, depth int)) *MarketDataService_FetchOrderBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MarketDataService_FetchOrderBook_Call) Return(_a0 *connector.OrderBook, _a1 error) *MarketDataService_FetchOrderBook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_FetchOrderBook_Call) RunAndReturn(run func(string, int) (*connector.OrderBook, error)) *MarketDataService_FetchOrderBook_Call {
	_c.Call.Return(run)
	return _c
}

// FetchPrice provides a mock function with given fields: symbol
func (_m *MarketDataService) FetchPrice(symbol string) (*connector.Price, error) {
	ret := _m.Called(symbol)

	if len(ret) == 0 {
		panic("no return value specified for FetchPrice")
	}

	var r0 *connector.Price
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*connector.Price, error)); ok {
		return rf(symbol)
	}
	if rf, ok := ret.Get(0).(func(string) *connector.Price); ok {
		r0 = rf(symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.Price)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_FetchPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPrice'
type MarketDataService_FetchPrice_Call struct {
	*mock.Call
}

// FetchPrice is a helper method to define mock.On call
//   - symbol string
func (_e *MarketDataService_Expecter) FetchPrice(symbol interface{}) *MarketDataService_FetchPrice_Call {
	return &MarketDataService_FetchPrice_Call{Call: _e.mock.On("FetchPrice", symbol)}
}

func (_c *MarketDataService_FetchPrice_Call) Run(run func(symbol string)) *MarketDataService_FetchPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MarketDataService_FetchPrice_Call) Return(_a0 *connector.Price, _a1 error) *MarketDataService_FetchPrice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_FetchPrice_Call) RunAndReturn(run func(string) (*connector.Price, error)) *MarketDataService_FetchPrice_Call {
	_c.Call.Return(run)
	return _c
}

// FetchRecentTrades provides a mock function with given fields: symbol, limit
func (_m *MarketDataService) FetchRecentTrades(symbol string, limit int) ([]connector.Trade, error) {
	ret := _m.Called(symbol, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchRecentTrades")
	}

	var r0 []connector.Trade
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]connector.Trade, error)); ok {
		return rf(symbol, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []connector.Trade); ok {
		r0 = rf(symbol, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Trade)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(symbol, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketDataService_FetchRecentTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRecentTrades'
type MarketDataService_FetchRecentTrades_Call struct {
	*mock.Call
}

// FetchRecentTrades is a helper method to define mock.On call
//   - symbol string
//   - limit int
func (_e *MarketDataService_Expecter) FetchRecentTrades(symbol interface{}, limit interface{}) *MarketDataService_FetchRecentTrades_Call {
	return &MarketDataService_FetchRecentTrades_Call{Call: _e.mock.On("FetchRecentTrades", symbol, limit)}
}

func (_c *MarketDataService_FetchRecentTrades_Call) Run(run func(symbol string, limit int)) *MarketDataService_FetchRecentTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MarketDataService_FetchRecentTrades_Call) Return(_a0 []connector.Trade, _a1 error) *MarketDataService_FetchRecentTrades_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketDataService_FetchRecentTrades_Call) RunAndReturn(run func(string, int) ([]connector.Trade, error)) *MarketDataService_FetchRecentTrades_Call {
	_c.Call.Return(run)
	return _c
}

// Initialize provides a mock function with given fields: config
func (_m *MarketDataService) Initialize(config *data.Config) error {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*data.Config) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarketDataService_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MarketDataService_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - config *data.Config
func (_e *MarketDataService_Expecter) Initialize(config interface{}) *MarketDataService_Initialize_Call {
	return &MarketDataService_Initialize_Call{Call: _e.mock.On("Initialize", config)}
}

func (_c *MarketDataService_Initialize_Call) Run(run func(config *data.Config)) *MarketDataService_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*data.Config))
	})
	return _c
}

func (_c *MarketDataService_Initialize_Call) Return(_a0 error) *MarketDataService_Initialize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MarketDataService_Initialize_Call) RunAndReturn(run func(*data.Config) error) *MarketDataService_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMarketDataService creates a new instance of MarketDataService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketDataService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketDataService {
	mock := &MarketDataService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
