// Code generated by mockery v2.53.5. DO NOT EDIT.

package adaptors

import (
	hyperliquid "github.com/sonirico/go-hyperliquid"
	mock "github.com/stretchr/testify/mock"
)

// ExchangeClient is an autogenerated mock type for the ExchangeClient type
type ExchangeClient struct {
	mock.Mock
}

type ExchangeClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ExchangeClient) EXPECT() *ExchangeClient_Expecter {
	return &ExchangeClient_Expecter{mock: &_m.Mock}
}

// Configure provides a mock function with given fields: baseURL, privateKey, vaultAddr, accountAddr
func (_m *ExchangeClient) Configure(baseURL string, privateKey string, vaultAddr string, accountAddr string) error {
	ret := _m.Called(baseURL, privateKey, vaultAddr, accountAddr)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(baseURL, privateKey, vaultAddr, accountAddr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExchangeClient_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type ExchangeClient_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - baseURL string
//   - privateKey string
//   - vaultAddr string
//   - accountAddr string
func (_e *ExchangeClient_Expecter) Configure(baseURL interface{}, privateKey interface{}, vaultAddr interface{}, accountAddr interface{}) *ExchangeClient_Configure_Call {
	return &ExchangeClient_Configure_Call{Call: _e.mock.On("Configure", baseURL, privateKey, vaultAddr, accountAddr)}
}

func (_c *ExchangeClient_Configure_Call) Run(run func(baseURL string, privateKey string, vaultAddr string, accountAddr string)) *ExchangeClient_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ExchangeClient_Configure_Call) Return(_a0 error) *ExchangeClient_Configure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExchangeClient_Configure_Call) RunAndReturn(run func(string, string, string, string) error) *ExchangeClient_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// GetExchange provides a mock function with no fields
func (_m *ExchangeClient) GetExchange() (*hyperliquid.Exchange, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExchange")
	}

	var r0 *hyperliquid.Exchange
	var r1 error
	if rf, ok := ret.Get(0).(func() (*hyperliquid.Exchange, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *hyperliquid.Exchange); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hyperliquid.Exchange)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExchangeClient_GetExchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExchange'
type ExchangeClient_GetExchange_Call struct {
	*mock.Call
}

// GetExchange is a helper method to define mock.On call
func (_e *ExchangeClient_Expecter) GetExchange() *ExchangeClient_GetExchange_Call {
	return &ExchangeClient_GetExchange_Call{Call: _e.mock.On("GetExchange")}
}

func (_c *ExchangeClient_GetExchange_Call) Run(run func()) *ExchangeClient_GetExchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExchangeClient_GetExchange_Call) Return(_a0 *hyperliquid.Exchange, _a1 error) *ExchangeClient_GetExchange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExchangeClient_GetExchange_Call) RunAndReturn(run func() (*hyperliquid.Exchange, error)) *ExchangeClient_GetExchange_Call {
	_c.Call.Return(run)
	return _c
}

// IsConfigured provides a mock function with no fields
func (_m *ExchangeClient) IsConfigured() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConfigured")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ExchangeClient_IsConfigured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConfigured'
type ExchangeClient_IsConfigured_Call struct {
	*mock.Call
}

// IsConfigured is a helper method to define mock.On call
func (_e *ExchangeClient_Expecter) IsConfigured() *ExchangeClient_IsConfigured_Call {
	return &ExchangeClient_IsConfigured_Call{Call: _e.mock.On("IsConfigured")}
}

func (_c *ExchangeClient_IsConfigured_Call) Run(run func()) *ExchangeClient_IsConfigured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExchangeClient_IsConfigured_Call) Return(_a0 bool) *ExchangeClient_IsConfigured_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExchangeClient_IsConfigured_Call) RunAndReturn(run func() bool) *ExchangeClient_IsConfigured_Call {
	_c.Call.Return(run)
	return _c
}

// NewExchangeClient creates a new instance of ExchangeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExchangeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExchangeClient {
	mock := &ExchangeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
