// Code generated by mockery v2.53.5. DO NOT EDIT.

package adaptors

import (
	hyperliquid "github.com/sonirico/go-hyperliquid"
	mock "github.com/stretchr/testify/mock"
)

// InfoClient is an autogenerated mock type for the InfoClient type
type InfoClient struct {
	mock.Mock
}

type InfoClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InfoClient) EXPECT() *InfoClient_Expecter {
	return &InfoClient_Expecter{mock: &_m.Mock}
}

// Configure provides a mock function with given fields: baseURL
func (_m *InfoClient) Configure(baseURL string) error {
	ret := _m.Called(baseURL)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(baseURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InfoClient_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type InfoClient_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - baseURL string
func (_e *InfoClient_Expecter) Configure(baseURL interface{}) *InfoClient_Configure_Call {
	return &InfoClient_Configure_Call{Call: _e.mock.On("Configure", baseURL)}
}

func (_c *InfoClient_Configure_Call) Run(run func(baseURL string)) *InfoClient_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *InfoClient_Configure_Call) Return(_a0 error) *InfoClient_Configure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InfoClient_Configure_Call) RunAndReturn(run func(string) error) *InfoClient_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// GetInfo provides a mock function with no fields
func (_m *InfoClient) GetInfo() (*hyperliquid.Info, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 *hyperliquid.Info
	var r1 error
	if rf, ok := ret.Get(0).(func() (*hyperliquid.Info, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *hyperliquid.Info); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hyperliquid.Info)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InfoClient_GetInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInfo'
type InfoClient_GetInfo_Call struct {
	*mock.Call
}

// GetInfo is a helper method to define mock.On call
func (_e *InfoClient_Expecter) GetInfo() *InfoClient_GetInfo_Call {
	return &InfoClient_GetInfo_Call{Call: _e.mock.On("GetInfo")}
}

func (_c *InfoClient_GetInfo_Call) Run(run func()) *InfoClient_GetInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InfoClient_GetInfo_Call) Return(_a0 *hyperliquid.Info, _a1 error) *InfoClient_GetInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InfoClient_GetInfo_Call) RunAndReturn(run func() (*hyperliquid.Info, error)) *InfoClient_GetInfo_Call {
	_c.Call.Return(run)
	return _c
}

// IsConfigured provides a mock function with no fields
func (_m *InfoClient) IsConfigured() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConfigured")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// InfoClient_IsConfigured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConfigured'
type InfoClient_IsConfigured_Call struct {
	*mock.Call
}

// IsConfigured is a helper method to define mock.On call
func (_e *InfoClient_Expecter) IsConfigured() *InfoClient_IsConfigured_Call {
	return &InfoClient_IsConfigured_Call{Call: _e.mock.On("IsConfigured")}
}

func (_c *InfoClient_IsConfigured_Call) Run(run func()) *InfoClient_IsConfigured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InfoClient_IsConfigured_Call) Return(_a0 bool) *InfoClient_IsConfigured_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InfoClient_IsConfigured_Call) RunAndReturn(run func() bool) *InfoClient_IsConfigured_Call {
	_c.Call.Return(run)
	return _c
}

// NewInfoClient creates a new instance of InfoClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInfoClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InfoClient {
	mock := &InfoClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
